// <auto-generated />
using System;
using Fookbase.Api.Modules.Messages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fookbase.Api.Modules.Messages.Data.Migrations;

[DbContext(typeof(MessagesDbContext))]
partial class MessagesDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Fookbase.Api.Modules.Messages.Entities.Conversation", builder =>
        {
            builder.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");
            builder.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            builder.Property<DateTimeOffset>("LastMessageAtUtc").HasColumnType("timestamp with time zone");
            builder.Property<Guid>("UserId1").HasColumnType("uuid");
            builder.Property<Guid>("UserId2").HasColumnType("uuid");
            builder.HasKey("Id");
            builder.HasIndex("UserId1", "LastMessageAtUtc");
            builder.HasIndex("UserId1", "UserId2").IsUnique();
            builder.HasIndex("UserId2", "LastMessageAtUtc");
            builder.ToTable("Conversations", null, table =>
            {
                table.HasCheckConstraint("CK_Conversations_CanonicalPair", "\"UserId1\" < \"UserId2\"");
            });
        });

        modelBuilder.Entity("Fookbase.Api.Modules.Messages.Entities.Message", builder =>
        {
            builder.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");
            builder.Property<Guid>("ConversationId").HasColumnType("uuid");
            builder.Property<string>("Content")
                .IsRequired()
                .HasMaxLength(5000)
                .HasColumnType("character varying(5000)");
            builder.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            builder.Property<DateTimeOffset?>("ReadAtUtc").HasColumnType("timestamp with time zone");
            builder.Property<Guid>("SenderUserId").HasColumnType("uuid");
            builder.HasKey("Id");
            builder.HasIndex("ConversationId", "CreatedAtUtc");
            builder.HasIndex("ConversationId", "ReadAtUtc");
            builder.ToTable("Messages");
        });
#pragma warning restore 612, 618
    }
}
