import { useState } from 'react';
import { Alert } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { authApi, type TwoFactorSetup } from '../../api/auth';
import { clearSession, saveSession } from '../../auth/session';
import { useAuth } from '../../auth/AuthProvider';
import { Button, Card, ErrorNotice, Field, Label, Loading, Screen } from '../../components/ui';
export default function Security() {
  const { session } = useAuth(); const cache = useQueryClient(); const [current, setCurrent] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [code, setCode] = useState('');
  const [setup,setSetup] = useState<TwoFactorSetup | null>(null); const [recovery,setRecovery] = useState<string[]>([]);
  const state = useQuery({ queryKey:['security', session?.user.id], queryFn:authApi.security });
  const sessions = useQuery({ queryKey:['sessions',session?.user.id], queryFn:authApi.sessions });
  const action = useMutation({ mutationFn:(fn:()=>Promise<unknown>)=>fn(), onSuccess:()=>cache.invalidateQueries() });
  return <Screen><Label title>Bảo mật tài khoản</Label><Card><Label title>Đổi mật khẩu</Label><Field label="Mật khẩu hiện tại" value={current} onChangeText={setCurrent} secureTextEntry /><Field label="Mật khẩu mới" value={password} onChangeText={setPassword} secureTextEntry /><Field label="Nhập lại mật khẩu mới" value={confirm} onChangeText={setConfirm} secureTextEntry /><Button title="Đổi mật khẩu" disabled={action.isPending || !current || !password || password !== confirm} onPress={() => action.mutate(async()=>{ const s=await authApi.changePassword({currentPassword:current,newPassword:password,confirmPassword:confirm});await saveSession(s);setCurrent('');setPassword('');setConfirm(''); })} /></Card>
    <Card><Label title>Xác minh hai bước</Label>{state.isPending && <Loading />}{state.error && <ErrorNotice error={state.error} retry={() => void state.refetch()} />}{state.data && <><Label>{state.data.twoFactorEnabled ? 'Đang bật' : 'Chưa bật'}</Label>{state.data.twoFactorEnabled ? <><Field label="Mật khẩu để tắt xác minh hai bước" secureTextEntry value={current} onChangeText={setCurrent} /><Button secondary title="Tắt xác minh hai bước" disabled={action.isPending || !current} onPress={() => Alert.alert('Tắt xác minh hai bước?', 'Tài khoản sẽ chỉ được bảo vệ bằng mật khẩu.', [{text:'Hủy',style:'cancel'},{text:'Tắt',onPress:()=>action.mutate(async()=>{await authApi.disableTwoFactor(current);setCurrent('');})}])} /><Button secondary title="Tạo lại mã khôi phục" disabled={action.isPending || recovery.length > 0} onPress={()=>Alert.alert('Thay mã khôi phục?', 'Các mã cũ sẽ không dùng được nữa.', [{text:'Hủy',style:'cancel'},{text:'Tạo mã mới',onPress:()=>action.mutate(async()=>{setRecovery((await authApi.regenerateRecoveryCodes()).recoveryCodes);})}])} /></> : <Button title="Thiết lập xác minh hai bước" disabled={action.isPending} onPress={()=>action.mutate(async()=>{setSetup(await authApi.setupTwoFactor());})} />}</>}
      {setup && <><Label>Nhập khóa này vào ứng dụng xác thực, rồi điền mã 6 số:</Label><Label>{setup.sharedKey}</Label><Field label="Mã xác thực" value={code} onChangeText={setCode} keyboardType="number-pad" /><Button title="Bật xác minh hai bước" disabled={action.isPending || !code.trim()} onPress={()=>action.mutate(async()=>{setRecovery((await authApi.enableTwoFactor(code)).recoveryCodes);setSetup(null);setCode('');})} /></>}
      {recovery.length > 0 && <><Label>Hãy lưu các mã khôi phục ở nơi an toàn. Mỗi mã chỉ dùng một lần.</Label>{recovery.map(r=><Label key={r}>{r}</Label>)}<Button title="Tôi đã lưu mã khôi phục" onPress={()=>setRecovery([])} /></>}
    </Card><Label title>Phiên đăng nhập</Label>{sessions.error && <ErrorNotice error={sessions.error} retry={()=>void sessions.refetch()} />}{sessions.data?.map(s=><Card key={s.sessionId}><Label>{s.device || 'Thiết bị không xác định'}{s.isCurrent ? ' · Thiết bị này' : ''}</Label><Label muted>{new Date(s.lastSeenAtUtc).toLocaleString('vi-VN')}</Label><Button secondary title="Đăng xuất phiên này" disabled={action.isPending} onPress={()=>action.mutate(async()=>{await authApi.revokeSession(s.sessionId);if(s.isCurrent)await clearSession();})} /></Card>)}<Button secondary title="Đăng xuất các thiết bị khác" disabled={action.isPending} onPress={()=>action.mutate(authApi.revokeOtherSessions)} />{action.error && <ErrorNotice error={action.error} />}{action.isSuccess && <Label>Đã cập nhật.</Label>}
  </Screen>;
}
