using System.Text;
using Fookbase.Api.Modules.Events.DTOs.Requests;
using Fookbase.Api.Modules.Events.DTOs.Responses;
using Fookbase.Api.Modules.Events.Entities;
using Fookbase.Api.Modules.Friends.Entities;
using Fookbase.Api.Modules.Media.Entities;
using Fookbase.Api.Modules.Notifications.Entities;
using Fookbase.Api.Modules.Notifications.Services;
using Fookbase.Api.Shared.Common;
using Fookbase.Api.Modules.Posts.DTOs.Responses;
using Fookbase.Api.Modules.Posts.Entities;
using Fookbase.Api.Modules.Posts.Services;
using Fookbase.Api.Persistence;
using Microsoft.EntityFrameworkCore;
namespace Fookbase.Api.Modules.Events.Services;
public sealed class EventsService(FookbaseDbContext db, EventAccessService access, NotificationService notifications,
    PostsService posts, Fookbase.Api.Modules.Media.Services.MediaService media, SocialInteractionsService interactions, TimeProvider time)
{
    public const int DefaultPageSize=20, MaximumPageSize=100;
    public async Task<ApplicationResult<EventResponse>> CreateAsync(Guid actor, CreateEventRequest request, CancellationToken ct=default)
    { if (!TryEnum(request.HostType,out EventHostType hostType)||!TryEnum(request.Privacy,out EventPrivacy privacy)||!TryEnum(request.LocationType,out EventLocationType locationType)||
          (!string.IsNullOrWhiteSpace(request.Status)&&(!TryEnum(request.Status,out EventStatus parsedStatus)||parsedStatus==EventStatus.Cancelled))) return Bad<EventResponse>("invalid_event","Event host, privacy, location, or status is invalid.");
      var status=string.IsNullOrWhiteSpace(request.Status)?EventStatus.Published:Enum.Parse<EventStatus>(request.Status,true); var hostId=hostType==EventHostType.User?actor:request.HostId;
      if (hostId is null || !await CanCreateForHostAsync(actor,hostType,hostId.Value,ct)) return Forbidden<EventResponse>();
      if (request.CoverMediaId is not null) { var cover=await ValidateCoverAsync(actor,request.CoverMediaId.Value,ct); if (cover is not null) return ApplicationResult<EventResponse>.Failure(cover); }
      try { await using var tx=await db.Database.BeginTransactionAsync(ct); var item=Event.Create(Guid.NewGuid(),request.Name,request.Description,hostType,hostId.Value,actor,privacy,locationType,request.LocationName,request.Address,request.OnlineUrl,request.StartsAtUtc,request.EndsAtUtc,status,time.GetUtcNow()); db.Events.Add(item); await SyncCoverAsync(item.Id,request.CoverMediaId,ct); item.SetCover(request.CoverMediaId,time.GetUtcNow()); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return ApplicationResult<EventResponse>.Success(await ToResponseAsync(item,actor,ct)); }
      catch (ArgumentException ex) { return Bad<EventResponse>("invalid_event",ex.Message); } }
    public async Task<ApplicationResult<EventResponse>> GetAsync(Guid id, Guid? viewer, CancellationToken ct=default)
    { var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct); if(item is null || !await access.CanViewAsync(item,viewer,ct)) return NotFound<EventResponse>(); return ApplicationResult<EventResponse>.Success(await ToResponseAsync(item,viewer,ct)); }
    public async Task<ApplicationResult<Guid>> GetCoverMediaIdAsync(Guid id, Guid? viewer, CancellationToken ct=default)
    { var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct); if(item?.CoverMediaId is null || !await access.CanViewAsync(item,viewer,ct)) return NotFound<Guid>(); return ApplicationResult<Guid>.Success(item.CoverMediaId.Value); }
    public async Task<ApplicationResult<EventResponse>> UpdateAsync(Guid actor, Guid id, UpdateEventRequest request, CancellationToken ct=default)
    { var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct); if(item is null) return NotFound<EventResponse>(); if(!await access.CanManageAsync(item,actor,ct)) return Forbidden<EventResponse>();
      if(!TryEnum(request.Privacy,out EventPrivacy privacy)||!TryEnum(request.LocationType,out EventLocationType location)) return Bad<EventResponse>("invalid_event","Privacy or location type is invalid.");
      var desired=request.RemoveCover?null:request.CoverMediaId??item.CoverMediaId; if(request.CoverMediaId is not null){var cover=await ValidateCoverAsync(actor,request.CoverMediaId.Value,ct);if(cover is not null)return ApplicationResult<EventResponse>.Failure(cover);} try { var changed=item.StartsAtUtc!=request.StartsAtUtc.ToUniversalTime()||item.EndsAtUtc!=request.EndsAtUtc?.ToUniversalTime()||item.LocationType!=location||item.LocationName!=request.LocationName?.Trim()||item.Address!=request.Address?.Trim()||item.OnlineUrl!=request.OnlineUrl?.Trim(); await using var tx=await db.Database.BeginTransactionAsync(ct); item.Update(request.Name,request.Description,privacy,location,request.LocationName,request.Address,request.OnlineUrl,request.StartsAtUtc,request.EndsAtUtc,time.GetUtcNow()); item.SetCover(desired,time.GetUtcNow()); await SyncCoverAsync(id,desired,ct); if(changed) await NotifyParticipantsAsync(item,NotificationType.EventUpdated,ct); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return ApplicationResult<EventResponse>.Success(await ToResponseAsync(item,actor,ct)); } catch(ArgumentException ex){return Bad<EventResponse>("invalid_event",ex.Message);} }
    public async Task<ApplicationResult<EventResponse>> PublishAsync(Guid actor,Guid id,CancellationToken ct=default)=>await TransitionAsync(actor,id,false,ct);
    public async Task<ApplicationResult<EventResponse>> CancelAsync(Guid actor,Guid id,CancellationToken ct=default)=>await TransitionAsync(actor,id,true,ct);
    public async Task<ApplicationResult> DeleteAsync(Guid actor,Guid id,CancellationToken ct=default)
    { var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return NotFound();if(!await access.CanManageAsync(item,actor,ct))return Forbidden(); await using var tx=await db.Database.BeginTransactionAsync(ct);item.Delete(time.GetUtcNow());await SyncCoverAsync(id,null,ct);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return ApplicationResult.Success(); }
    public async Task<ApplicationResult<EventResponse>> RsvpAsync(Guid actor,Guid id,string status,CancellationToken ct=default)
    { if(!TryEnum(status,out EventParticipantStatus parsed))return Bad<EventResponse>("invalid_rsvp_status","RSVP status must be going or interested.");var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null||item.Status!=EventStatus.Published||!await access.CanViewAsync(item,actor,ct))return NotFound<EventResponse>();var existing=await db.EventParticipants.SingleOrDefaultAsync(x=>x.EventId==id&&x.UserId==actor,ct);if(existing is null)db.EventParticipants.Add(EventParticipant.Create(id,actor,parsed,time.GetUtcNow()));else existing.SetStatus(parsed,time.GetUtcNow());await db.SaveChangesAsync(ct);return ApplicationResult<EventResponse>.Success(await ToResponseAsync(item,actor,ct)); }
    public async Task<ApplicationResult> RemoveRsvpAsync(Guid actor,Guid id,CancellationToken ct=default)
    { var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null||item.Status!=EventStatus.Published||!await access.CanViewAsync(item,actor,ct))return NotFound();var row=await db.EventParticipants.SingleOrDefaultAsync(x=>x.EventId==id&&x.UserId==actor,ct);if(row is not null){db.EventParticipants.Remove(row);await db.SaveChangesAsync(ct);}return ApplicationResult.Success(); }
    public async Task<ApplicationResult<EventInvitationResponse>> InviteAsync(Guid actor,Guid id,Guid invitee,CancellationToken ct=default)
    { var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return NotFound<EventInvitationResponse>();if(item.Status!=EventStatus.Published||!await access.CanManageAsync(item,actor,ct))return Forbidden<EventInvitationResponse>();if(actor==invitee)return Bad<EventInvitationResponse>("self_invite","You cannot invite yourself.");if(!await db.Users.AsNoTracking().AnyAsync(x=>x.Id==invitee,ct))return NotFound<EventInvitationResponse>();if(await IsBlockedAsync(actor,invitee,ct))return Bad<EventInvitationResponse>("relationship_unavailable","This invitation is unavailable.",ApplicationErrorType.Conflict);if(await db.EventInvitations.AnyAsync(x=>x.EventId==id&&x.InviteeUserId==invitee&&x.Status==EventInvitationStatus.Pending,ct))return Bad<EventInvitationResponse>("event_invitation_pending","An invitation is already pending.",ApplicationErrorType.Conflict);var invitation=EventInvitation.Create(Guid.NewGuid(),id,actor,invitee,time.GetUtcNow());db.EventInvitations.Add(invitation);var notification=await notifications.QueueAsync(invitee,actor,NotificationType.EventInvite,NotificationEntityType.Event,invitation.Id,ct);await db.SaveChangesAsync(ct);if(notification is not null)await notifications.PublishAsync(notification,ct);return ApplicationResult<EventInvitationResponse>.Success(await ToInvitationAsync(invitation,actor,ct)); }
    public async Task<ApplicationResult<EventInvitationResponse>> RespondInviteAsync(Guid actor,Guid inviteId,bool accept,CancellationToken ct=default)
    { var invitation=await db.EventInvitations.SingleOrDefaultAsync(x=>x.Id==inviteId&&x.InviteeUserId==actor,ct);if(invitation is null)return NotFound<EventInvitationResponse>();var item=await Active().SingleOrDefaultAsync(x=>x.Id==invitation.EventId,ct);if(item is null||item.Status!=EventStatus.Published)return NotFound<EventInvitationResponse>();await using var tx=await db.Database.BeginTransactionAsync(ct);if(accept){invitation.Accept(time.GetUtcNow());var participant=await db.EventParticipants.SingleOrDefaultAsync(x=>x.EventId==item.Id&&x.UserId==actor,ct);if(participant is null)db.EventParticipants.Add(EventParticipant.Create(item.Id,actor,EventParticipantStatus.Going,time.GetUtcNow()));else participant.SetStatus(EventParticipantStatus.Going,time.GetUtcNow());}else invitation.Decline(time.GetUtcNow());await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return ApplicationResult<EventInvitationResponse>.Success(await ToInvitationAsync(invitation,actor,ct)); }
    public async Task<ApplicationResult<EventCursorPageResponse<EventResponse>>> GetMineAsync(Guid actor,string? cursor,int limit,CancellationToken ct=default)=> await ListAsync(Active().Where(x=>x.CreatedByUserId==actor|| (x.HostType==EventHostType.Group&&db.GroupMembers.Any(m=>m.GroupId==x.HostId&&m.UserId==actor&&(m.Role==Fookbase.Api.Modules.Groups.Entities.GroupMemberRole.Owner||m.Role==Fookbase.Api.Modules.Groups.Entities.GroupMemberRole.Admin||m.Role==Fookbase.Api.Modules.Groups.Entities.GroupMemberRole.Moderator))) || (x.HostType==EventHostType.Page&&db.PageMembers.Any(m=>m.PageId==x.HostId&&m.UserId==actor&&(m.Role==Fookbase.Api.Modules.Pages.Entities.PageRole.Owner||m.Role==Fookbase.Api.Modules.Pages.Entities.PageRole.Admin||m.Role==Fookbase.Api.Modules.Pages.Entities.PageRole.Editor)))),actor,cursor,limit,false,ct);
    public async Task<ApplicationResult<EventCursorPageResponse<EventResponse>>> UpcomingAsync(Guid actor,string? cursor,int limit,CancellationToken ct=default)=>await ListAsync(Active().Where(x=>x.StartsAtUtc>=time.GetUtcNow()&&(db.EventParticipants.Any(p=>p.EventId==x.Id&&p.UserId==actor)||x.CreatedByUserId==actor)),actor,cursor,limit,false,ct);
    public async Task<ApplicationResult<EventCursorPageResponse<EventResponse>>> DiscoverAsync(Guid actor,string? query,string? cursor,int limit,CancellationToken ct=default){var now=time.GetUtcNow();var q=Active().Where(x=>x.Status==EventStatus.Published&&x.Privacy==EventPrivacy.Public&&x.StartsAtUtc>=now);if(!string.IsNullOrWhiteSpace(query)){var term=query.Trim().ToLower();q=q.Where(x=>x.Name.ToLower().Contains(term)||(x.Description??"").ToLower().Contains(term)||(x.LocationName??"").ToLower().Contains(term));}return await ListAsync(q,actor,cursor,limit,false,ct);}
    public async Task<ApplicationResult<EventCursorPageResponse<EventInvitationResponse>>> InvitationsAsync(Guid actor,string? cursor,int limit,CancellationToken ct=default){if(!ValidLimit(limit))return Bad<EventCursorPageResponse<EventInvitationResponse>>("invalid_limit","Limit must be between 1 and 100.");var rows=await db.EventInvitations.AsNoTracking().Where(x=>x.InviteeUserId==actor&&x.Status==EventInvitationStatus.Pending).OrderByDescending(x=>x.CreatedAtUtc).ThenByDescending(x=>x.Id).Take(limit+1).ToListAsync(ct);return ApplicationResult<EventCursorPageResponse<EventInvitationResponse>>.Success(new(await Task.WhenAll(rows.Take(limit).Select(x=>ToInvitationAsync(x,actor,ct))),rows.Count>limit?Encode(rows[limit].CreatedAtUtc,rows[limit].Id):null));}
    public async Task<ApplicationResult<EventCursorPageResponse<EventParticipantResponse>>> ParticipantsAsync(Guid actor,Guid id,string? cursor,int limit,CancellationToken ct=default){var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null||!await access.CanViewAsync(item,actor,ct))return NotFound<EventCursorPageResponse<EventParticipantResponse>>();if(!ValidLimit(limit))return Bad<EventCursorPageResponse<EventParticipantResponse>>("invalid_limit","Limit must be between 1 and 100.");var rows=await (from p in db.EventParticipants.AsNoTracking() join u in db.UserProfiles.AsNoTracking() on p.UserId equals u.UserId where p.EventId==id&&!db.BlockedUsers.Any(b=>(b.BlockerUserId==actor&&b.BlockedUserId==p.UserId)||(b.BlockerUserId==p.UserId&&b.BlockedUserId==actor)) orderby p.RespondedAtUtc descending,p.UserId descending select new {p,u}).Take(limit+1).ToListAsync(ct);var items=rows.Take(limit).Select(x=>new EventParticipantResponse(x.p.UserId,x.u.Username,x.u.DisplayName,x.u.AvatarMediaId is null?x.u.AvatarUrl:$"/api/users/{x.p.UserId}/avatar",x.p.Status.ToString().ToLowerInvariant(),x.p.RespondedAtUtc)).ToList();return ApplicationResult<EventCursorPageResponse<EventParticipantResponse>>.Success(new(items,rows.Count>limit?Encode(rows[limit].p.RespondedAtUtc,rows[limit].p.UserId):null));}
    public async Task<ApplicationResult<EventCursorPageResponse<PostResponse>>> PostsAsync(Guid actor,Guid id,string? cursor,int limit,CancellationToken ct=default){var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null||!await access.CanViewAsync(item,actor,ct))return NotFound<EventCursorPageResponse<PostResponse>>();if(!ValidLimit(limit))return Bad<EventCursorPageResponse<PostResponse>>("invalid_limit","Limit must be between 1 and 100.");var rows=await db.Posts.AsNoTracking().Where(x=>x.ContainerType==PostContainerType.Event&&x.ContainerId==id&&x.DeletedAtUtc==null).OrderByDescending(x=>x.CreatedAtUtc).ThenByDescending(x=>x.Id).Take(limit+1).ToListAsync(ct);return ApplicationResult<EventCursorPageResponse<PostResponse>>.Success(new(await posts.LoadResponsesAsync(rows.Take(limit).ToList(),actor,ct),rows.Count>limit?Encode(rows[limit].CreatedAtUtc,rows[limit].Id):null));}
    public async Task<ApplicationResult<PostResponse>> CreatePostAsync(Guid actor,Guid id,CreateEventPostRequest request,CancellationToken ct=default){var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return NotFound<PostResponse>();if(!await access.CanPostAsync(item,actor,ct))return Forbidden<PostResponse>();var ids=request.MediaIds??[];var validation=posts.ValidatePostRequest(request.Content,"public",ids);if(!validation.Succeeded)return ApplicationResult<PostResponse>.Failure(validation.Error!);var mediaValidation=await media.ValidatePostMediaAsync(actor,ids,ct);if(!mediaValidation.Succeeded)return ApplicationResult<PostResponse>.Failure(mediaValidation.Error!);await using var tx=await db.Database.BeginTransactionAsync(ct);var created=await posts.CreatePostInContainerCoreAsync(actor,request.Content,PostPrivacy.Public,PostContainerType.Event,id,ids,ct);if(!created.Succeeded){await tx.RollbackAsync(ct);return ApplicationResult<PostResponse>.Failure(new ApplicationError("post_failed","Event post could not be created.",ApplicationErrorType.Conflict));}var refs=await media.SynchronizePostReferencesAsync(actor,created.Value!.Id,ids,ct);if(!refs.Succeeded){await tx.RollbackAsync(ct);return ApplicationResult<PostResponse>.Failure(refs.Error!);}await interactions.SynchronizePostMetadataAsync(created.Value.Id,actor,ct);await tx.CommitAsync(ct);return ApplicationResult<PostResponse>.Success((await posts.LoadResponsesAsync([await db.Posts.AsNoTracking().SingleAsync(x=>x.Id==created.Value.Id,ct)],actor,ct))[0]);}
    private IQueryable<Event> Active()=>db.Events.Where(x=>x.DeletedAtUtc==null);
    private async Task<ApplicationResult<EventResponse>> TransitionAsync(Guid actor,Guid id,bool cancel,CancellationToken ct){var item=await Active().SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return NotFound<EventResponse>();if(!await access.CanManageAsync(item,actor,ct))return Forbidden<EventResponse>();try{if(cancel){item.Cancel(time.GetUtcNow());await NotifyParticipantsAsync(item,NotificationType.EventCancelled,ct);}else item.Publish(time.GetUtcNow());await db.SaveChangesAsync(ct);return ApplicationResult<EventResponse>.Success(await ToResponseAsync(item,actor,ct));}catch(InvalidOperationException ex){return Bad<EventResponse>("invalid_event_status",ex.Message,ApplicationErrorType.Conflict);}}
    private async Task<bool> CanCreateForHostAsync(Guid actor,EventHostType type,Guid hostId,CancellationToken ct){var probe=Event.Create(Guid.NewGuid(),"probe",null,type,hostId,actor,EventPrivacy.Public,EventLocationType.Physical,null,null,null,time.GetUtcNow(),null,EventStatus.Draft,time.GetUtcNow());return await access.CanManageAsync(probe,actor,ct);}
    private async Task<ApplicationError?> ValidateCoverAsync(Guid actor,Guid mediaId,CancellationToken ct){var asset=await db.MediaAssets.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==mediaId,ct);return asset is null||asset.OwnerUserId!=actor||asset.MediaType!=MediaType.Image||asset.Status!=MediaStatus.Ready||asset.DeletedAtUtc is not null?new ApplicationError("invalid_event_cover","Event cover must be your ready image.",ApplicationErrorType.Validation):null;}
    private async Task SyncCoverAsync(Guid eventId,Guid? mediaId,CancellationToken ct){var old=await db.EventCoverMediaReferences.SingleOrDefaultAsync(x=>x.EventId==eventId,ct);if(old is not null)db.EventCoverMediaReferences.Remove(old);if(mediaId is not null)db.EventCoverMediaReferences.Add(EventCoverMediaReference.Create(eventId,mediaId.Value,time.GetUtcNow()));}
    private async Task NotifyParticipantsAsync(Event item,NotificationType type,CancellationToken ct){var userIds=await db.EventParticipants.AsNoTracking().Where(x=>x.EventId==item.Id).Select(x=>x.UserId).ToListAsync(ct);foreach(var userId in userIds)await notifications.QueueAsync(userId,item.CreatedByUserId,type,NotificationEntityType.Event,item.Id,ct);}
    private async Task<ApplicationResult<EventCursorPageResponse<EventResponse>>> ListAsync(IQueryable<Event> query,Guid actor,string? cursor,int limit,bool desc,CancellationToken ct){if(!ValidLimit(limit))return Bad<EventCursorPageResponse<EventResponse>>("invalid_limit","Limit must be between 1 and 100.");var rows=await query.OrderBy(x=>x.StartsAtUtc).ThenBy(x=>x.Id).Take(limit+1).ToListAsync(ct);return ApplicationResult<EventCursorPageResponse<EventResponse>>.Success(new(await Task.WhenAll(rows.Take(limit).Select(x=>ToResponseAsync(x,actor,ct))),rows.Count>limit?Encode(rows[limit].StartsAtUtc,rows[limit].Id):null));}
    private async Task<EventResponse> ToResponseAsync(Event item,Guid? viewer,CancellationToken ct){var host=await HostAsync(item,ct);var counts=await db.EventParticipants.AsNoTracking().Where(x=>x.EventId==item.Id).GroupBy(x=>x.Status).Select(x=>new{x.Key,Count=x.Count()}).ToListAsync(ct);var participant=viewer is null?null:await db.EventParticipants.AsNoTracking().SingleOrDefaultAsync(x=>x.EventId==item.Id&&x.UserId==viewer,ct);var manage=viewer is not null&&await access.CanManageAsync(item,viewer.Value,ct);var post=viewer is not null&&await access.CanPostAsync(item,viewer.Value,ct);return new(item.Id,item.Name,item.Description,host,item.Privacy.ToString().ToLowerInvariant(),item.LocationType.ToString().ToLowerInvariant(),item.LocationName,item.Address,item.OnlineUrl,item.StartsAtUtc,item.EndsAtUtc,item.Status.ToString().ToLowerInvariant(),item.CoverMediaId is null?null:$"/api/events/{item.Id}/cover",counts.Where(x=>x.Key==EventParticipantStatus.Going).Select(x=>x.Count).FirstOrDefault(),counts.Where(x=>x.Key==EventParticipantStatus.Interested).Select(x=>x.Count).FirstOrDefault(),participant?.Status.ToString().ToLowerInvariant(),manage,post,item.CreatedAtUtc,item.UpdatedAtUtc);}
    private async Task<EventHostResponse> HostAsync(Event item,CancellationToken ct){if(item.HostType==EventHostType.Group){var x=await db.Groups.AsNoTracking().Where(x=>x.Id==item.HostId).Select(x=>new{x.Name}).SingleOrDefaultAsync(ct);return new("group",item.HostId,x?.Name??"Group");}if(item.HostType==EventHostType.Page){var x=await db.Pages.AsNoTracking().Where(x=>x.Id==item.HostId).Select(x=>new{x.Name,x.Username,x.AvatarMediaId}).SingleOrDefaultAsync(ct);return new("page",item.HostId,x?.Name??"Page",x?.Username,x?.AvatarMediaId is null?null:$"/api/pages/{item.HostId}/avatar");}var u=await db.UserProfiles.AsNoTracking().Where(x=>x.UserId==item.HostId).Select(x=>new{x.DisplayName,x.Username,x.AvatarUrl,x.AvatarMediaId}).SingleOrDefaultAsync(ct);return new("user",item.HostId,u?.DisplayName??"User",u?.Username,u?.AvatarMediaId is null?u?.AvatarUrl:$"/api/users/{item.HostId}/avatar");}
    private async Task<EventInvitationResponse> ToInvitationAsync(EventInvitation invitation,Guid viewer,CancellationToken ct){var item=await Active().SingleOrDefaultAsync(x=>x.Id==invitation.EventId,ct);return new(invitation.Id,invitation.EventId,invitation.InviterUserId,invitation.InviteeUserId,invitation.Status.ToString().ToLowerInvariant(),invitation.CreatedAtUtc,invitation.RespondedAtUtc,item is null?null:await ToResponseAsync(item,viewer,ct));}
    private Task<bool> IsBlockedAsync(Guid a,Guid b,CancellationToken ct)=>db.BlockedUsers.AsNoTracking().AnyAsync(x=>(x.BlockerUserId==a&&x.BlockedUserId==b)||(x.BlockerUserId==b&&x.BlockedUserId==a),ct);
    private static bool ValidLimit(int n)=>n is >=1 and <=MaximumPageSize; private static string? Encode(DateTimeOffset at,Guid id)=>System.Convert.ToBase64String(Encoding.UTF8.GetBytes($"{at.UtcTicks}|{id}"));
    private static bool TryEnum<T>(string? raw,out T value) where T:struct,Enum=>Enum.TryParse(raw,true,out value)&&Enum.IsDefined(value); private static ApplicationResult<T> Bad<T>(string code,string message,ApplicationErrorType type=ApplicationErrorType.Validation)=>ApplicationResult<T>.Failure(new(code,message,type));private static ApplicationResult<T> NotFound<T>()=>Bad<T>("event_not_found","The event was not found.",ApplicationErrorType.NotFound);private static ApplicationResult NotFound()=>ApplicationResult.Failure(new("event_not_found","The event was not found.",ApplicationErrorType.NotFound));private static ApplicationResult<T> Forbidden<T>()=>Bad<T>("event_forbidden","You are not allowed to manage this event.",ApplicationErrorType.Forbidden);private static ApplicationResult Forbidden()=>ApplicationResult.Failure(new("event_forbidden","You are not allowed to manage this event.",ApplicationErrorType.Forbidden));
}
