export { default as FeedPage } from './feed/FeedPage'
export { default as ExplorePage } from './explore/ExplorePage'
export { default as GamesPage } from './games/GamesPage'
export { default as ProfilePage } from './profile/ProfilePage'
export { default as ReelsPage } from './reels/ReelsPage'
