import { useEffect, useState } from 'react'
import { authApi, type AuthSessionInfo, type RecoveryCodes, type SecurityState, type TwoFactorSetup } from '../../api/auth'
import { useAuth } from '../../auth/useAuth'
import { Mascot } from 'page-mascot'

export default function SecuritySettingsPage() {
  const { changePassword } = useAuth(); const [security, setSecurity] = useState<SecurityState | null>(null); const [sessions, setSessions] = useState<AuthSessionInfo[]>([]); const [setup, setSetup] = useState<TwoFactorSetup | null>(null); const [code, setCode] = useState(''); const [codes, setCodes] = useState<RecoveryCodes | null>(null); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState('')
  const load = () => { void authApi.security().then(setSecurity); void authApi.sessions().then(setSessions) }; useEffect(load, [])
  return <main className="mx-auto max-w-2xl space-y-6 p-6 text-text"><div className="flex items-center gap-4"><Mascot directions="/mascots/knight-directions.webp" reactions="/mascots/knight-reactions.webp" size={64} label="Security Knight Mascot" /><h1 className="text-2xl font-bold">Bảo mật</h1></div><section className="rounded-xl border border-border bg-surface p-4"><h2 className="font-bold">Đổi mật khẩu</h2><input className="m-1 rounded bg-surface-2 p-2" type="password" placeholder="Mật khẩu hiện tại" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} /><input className="m-1 rounded bg-surface-2 p-2" type="password" placeholder="Mật khẩu mới" value={newPassword} onChange={e => setNewPassword(e.target.value)} /><button className="rounded bg-primary px-3 py-2 text-white" onClick={() => void changePassword({ currentPassword, newPassword, confirmPassword: newPassword })}>Đổi</button></section><section className="rounded-xl border border-border bg-surface p-4"><h2 className="font-bold">Phiên hoạt động ({security?.activeSessionCount ?? 0})</h2>{sessions.map(s => <div key={s.sessionId} className="flex justify-between py-2"><span>{s.device ?? 'Thiết bị không xác định'} {s.isCurrent && '(hiện tại)'}</span>{!s.isCurrent && <button onClick={() => void authApi.revokeSession(s.sessionId).then(load)}>Thu hồi</button>}</div>)}<button onClick={() => void authApi.revokeOtherSessions().then(load)}>Thu hồi phiên khác</button></section><section className="rounded-xl border border-border bg-surface p-4"><h2 className="font-bold">Xác thực hai bước</h2>{!security?.twoFactorEnabled && !setup && <button onClick={() => void authApi.setupTwoFactor().then(setSetup)}>Thiết lập</button>}{setup && <><p className="break-all text-sm">{setup.otpauthUri}</p><code>{setup.sharedKey}</code><input className="m-2 rounded bg-surface-2 p-2" placeholder="Mã xác thực" value={code} onChange={e => setCode(e.target.value)} /><button onClick={() => void authApi.enableTwoFactor(code).then(setCodes).then(load)}>Bật 2FA</button></>}{security?.twoFactorEnabled && <button onClick={() => void authApi.regenerateRecoveryCodes().then(setCodes)}>Tạo lại recovery codes</button>}{codes && <p className="mt-3 rounded bg-yellow-100 p-3 text-black">Lưu an toàn, chỉ hiển thị một lần: {codes.recoveryCodes.join(', ')}</p>}</section></main>
}
