import assert from 'node:assert/strict'
import { postFixtures, postId, viewerId } from './postInteractionsFixture.mjs'

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright')
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE, args: ['--no-sandbox'] })
const baseUrl = process.env.POST_BASE_URL ?? 'http://127.0.0.1:5183'
const failures = []
const passed = []
const trackErrors = (page) => {
  page.on('pageerror', (error) => failures.push(error.stack))
  page.on('console', (message) => {
    if (message.type() !== 'error' && message.type() !== 'warning') return
    if (/connection was stopped during negotiation|HttpConnection before stop\(\)/.test(message.text())) return
    // API failures are deliberately injected to verify rollback and error recovery.
    if (/503/.test(message.text()) && message.location().url.includes(`/api/posts/${postId}`)) return
    failures.push(`${message.type()}: ${message.text()}`)
  })
}
const check = async (name, run) => { await run(); passed.push(name); console.log(`PASS ${name}`) }
const until = async (checkValue) => {
  for (let attempt = 0; attempt < 200; attempt++) {
    if (await checkValue()) return
    await new Promise((resolve) => setTimeout(resolve, 30))
  }
  assert.fail('Condition did not settle')
}

try {
  const context = await browser.newContext({ viewport: { width: 1366, height: 900 } })
  const state = await postFixtures(context)
  const page = await context.newPage()
  trackErrors(page)
  await page.goto(`${baseUrl}/posts/${postId}`)
  const reaction = page.locator('[data-post-reaction]').first()
  await reaction.waitFor()
  await check('keyboard opens a freshly mounted picker with usable focus', async () => {
    await reaction.focus()
    await reaction.press('ArrowDown')
    assert.equal(await page.locator(':focus').getAttribute('aria-label'), 'Thích')
    await page.keyboard.press('Escape')
  })
  await check('desktop picker appears above the button without moving the card', async () => {
    const before = await page.locator('article').last().boundingBox()
    const button = await reaction.boundingBox()
    await reaction.hover()
    const menu = page.getByRole('menu', { name: 'Chọn cảm xúc', exact: true })
    await menu.waitFor()
    await page.waitForTimeout(200)
    const popup = await menu.boundingBox()
    assert.ok(popup.y + popup.height <= button.y)
    assert.deepEqual(await page.locator('article').last().boundingBox(), before)
    assert.equal(await menu.getByRole('menuitemradio').count(), 6)
  })
  await check('optimistic reaction, change and removal use existing API', async () => {
    await page.getByRole('menuitemradio', { name: 'Yêu thích', exact: true }).click()
    assert.equal(await reaction.getAttribute('aria-pressed'), 'true')
    assert.match(await reaction.innerText(), /Yêu thích/)
    await until(() => state.post.viewerReaction === 'love')
    await reaction.hover()
    await reaction.focus()
    await reaction.press('ArrowDown')
    assert.equal(await page.locator(':focus').getAttribute('aria-label'), 'Yêu thích')
    await page.getByRole('menuitemradio', { name: 'Wow', exact: true }).click()
    assert.match(await reaction.innerText(), /Wow/)
    await until(() => state.post.viewerReaction === 'wow')
    await reaction.click()
    assert.equal(await reaction.getAttribute('aria-pressed'), 'false')
    await until(() => state.post.viewerReaction === null)
    assert.deepEqual(state.post.reactionCounts, { like: 2, love: 1, wow: 0 })
  })
  await check('rapid reaction changes coalesce to the final intent without counter drift', async () => {
    state.reactionDelay = 1_000
    const before = state.writes.filter((write) => write.action === 'reaction').length
    const choose = async (label) => {
      await reaction.focus()
      await reaction.press('ArrowDown')
      await page.getByRole('menuitemradio', { name: label, exact: true }).click()
    }
    await choose('Yêu thích')
    await choose('Wow')
    await choose('Wow')
    assert.equal(await reaction.getAttribute('aria-pressed'), 'false')
    assert.equal(await page.getByRole('button', { name: 'Xem 3 cảm xúc', exact: true }).count(), 1)
    await until(() => state.writes.filter((write) => write.action === 'reaction').length >= before + 2 && state.post.viewerReaction === null)
    assert.deepEqual(state.writes.filter((write) => write.action === 'reaction').slice(before).map((write) => write.type), ['love', null])
    state.reactionDelay = 350
  })
  await check('reaction failure restores the exact previous vote and counter with one toast', async () => {
    state.failReaction = true
    await reaction.focus()
    await reaction.press('ArrowDown')
    await page.getByRole('menuitemradio', { name: 'Yêu thích', exact: true }).click()
    assert.equal(await reaction.getAttribute('aria-pressed'), 'true')
    assert.equal(await page.getByRole('button', { name: 'Xem 4 cảm xúc', exact: true }).count(), 1)
    await until(async () => await reaction.getAttribute('aria-pressed') === 'false')
    assert.equal(await page.getByRole('button', { name: 'Xem 3 cảm xúc', exact: true }).count(), 1)
    assert.equal(state.post.viewerReaction, null)
    assert.equal(await page.getByRole('status').filter({ hasText: 'Không thể lưu cảm xúc thử nghiệm.' }).count(), 1)
    state.failReaction = false
  })
  await check('reaction picker supports arrows, Escape and focus return', async () => {
    await reaction.focus()
    await reaction.press('ArrowDown')
    assert.equal(await page.locator(':focus').getAttribute('aria-label'), 'Thích')
    await page.keyboard.press('ArrowRight')
    assert.equal(await page.locator(':focus').getAttribute('aria-label'), 'Yêu thích')
    await page.keyboard.press('Escape')
    assert.equal(await reaction.getAttribute('aria-expanded'), 'false')
    assert.equal(await reaction.evaluate((button) => button === document.activeElement), true)
  })
  await check('post dropdown supports outside click, keyboard and Escape', async () => {
    const trigger = page.getByRole('button', { name: 'Tùy chọn khác', exact: true })
    await trigger.click()
    const menu = page.getByRole('menu', { name: 'Tùy chọn khác', exact: true })
    await menu.waitFor()
    assert.equal(await page.locator(':focus').getAttribute('role'), 'menuitem')
    await page.keyboard.press('End')
    assert.equal(await page.locator(':focus').innerText(), 'Xóa')
    await page.keyboard.press('Escape')
    assert.equal(await trigger.getAttribute('aria-expanded'), 'false')
    assert.equal(await trigger.evaluate((button) => button === document.activeElement), true)
    await trigger.press('ArrowDown')
    await menu.waitFor()
    await page.mouse.click(10, 400)
    assert.equal(await trigger.getAttribute('aria-expanded'), 'false')
  })
  await check('reduced motion disables picker and vote animations', async () => {
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await reaction.focus()
    await reaction.press('ArrowDown')
    const animation = await page.locator('.post-reaction-picker').evaluate((element) => getComputedStyle(element).animationName)
    assert.equal(animation, 'none')
    await page.keyboard.press('Escape')
  })
  await check('comments appear immediately and double submit creates one real comment', async () => {
    state.commentDelay = 700
    await page.getByRole('button', { name: 'Bình luận', exact: true }).first().click()
    const dialog = page.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    await dialog.waitFor()
    const input = dialog.getByRole('textbox', { name: 'Viết bình luận', exact: true })
    await input.fill('Bình luận tức thì')
    await input.press('Enter')
    assert.equal(await input.inputValue(), '')
    assert.equal(await dialog.locator('[data-comment-id][aria-busy="true"]').count(), 1)
    await dialog.getByRole('form', { name: 'Gửi bình luận' }).evaluate((form) => {
      form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))
      form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))
    })
    await until(() => state.comments.length === 1)
    await until(async () => await dialog.locator('[data-comment-id][aria-busy="true"]').count() === 0)
    assert.equal(await dialog.locator('[data-comment-id]').count(), 1)
    assert.equal(state.writes.filter((write) => write.action === 'comment').length, 1)
    assert.match(await page.locator('article').last().innerText(), /1 bình luận/)
    await page.getByRole('button', { name: 'Đóng bình luận', exact: true }).click()
  })
  await check('failed comment rolls back row/count and restores unchanged input', async () => {
    state.failComment = true
    state.commentDelay = 500
    await page.getByRole('button', { name: 'Bình luận', exact: true }).first().click()
    const dialog = page.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    const input = dialog.getByRole('textbox', { name: 'Viết bình luận', exact: true })
    await input.fill('Bản nháp cần giữ')
    await input.press('Enter')
    assert.equal(await dialog.locator('[data-comment-id]').count(), 2)
    await until(async () => await input.inputValue() === 'Bản nháp cần giữ')
    assert.equal(await dialog.locator('[data-comment-id]').count(), 1)
    assert.match(await page.locator('article').last().innerText(), /1 bình luận/)
    assert.equal(await page.getByRole('status').filter({ hasText: 'Không thể gửi bình luận thử nghiệm.' }).count(), 1)
    await input.fill('Bản nháp tiếp theo')
    await input.press('Enter')
    await input.fill('Đang viết nội dung khác')
    await until(async () => await dialog.locator('[data-comment-id][aria-busy="true"]').count() === 0)
    assert.equal(await input.inputValue(), 'Đang viết nội dung khác')
    await page.getByRole('button', { name: 'Đóng bình luận', exact: true }).click()
    state.failComment = false
  })
  await check('nested comment dialogs trap focus and Escape closes only the top dialog', async () => {
    await page.getByRole('button', { name: 'Bình luận', exact: true }).first().click()
    const discussion = page.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    await discussion.getByRole('button', { name: 'Sửa', exact: true }).first().click()
    const editor = page.getByRole('dialog', { name: 'Chỉnh sửa bình luận', exact: true })
    await editor.waitFor()
    assert.equal(await editor.getByRole('textbox').evaluate((element) => element === document.activeElement), true)
    await page.keyboard.press('Shift+Tab')
    assert.equal(await page.locator(':focus').innerText(), 'Lưu')
    await page.keyboard.press('Escape')
    assert.equal(await editor.count(), 0)
    assert.equal(await discussion.count(), 1)
    await discussion.getByRole('button', { name: /^Xem \d+ cảm xúc$/ }).click()
    const reactors = page.getByRole('dialog', { name: 'Người đã bày tỏ cảm xúc', exact: true })
    await reactors.waitFor()
    await page.keyboard.press('Escape')
    assert.equal(await reactors.count(), 0)
    assert.equal(await discussion.count(), 1)
    await page.keyboard.press('Escape')
    assert.equal(await discussion.count(), 0)
    assert.equal(await page.evaluate(() => document.body.style.overflow), '')
  })
  await check('metadata save is guarded, failures use toast and preserve current interactions', async () => {
    const trigger = page.getByRole('button', { name: 'Tùy chọn khác', exact: true })
    await trigger.click()
    await page.getByRole('menuitem', { name: 'Chỉnh sửa bài viết', exact: true }).click()
    const editor = page.getByRole('dialog', { name: 'Chỉnh sửa bài viết', exact: true })
    await editor.getByRole('textbox').fill('Bài viết đã sửa')
    await editor.locator('form').evaluate((form) => {
      form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))
      form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))
    })
    assert.equal(await editor.getByRole('button', { name: 'Lưu', exact: true }).isDisabled(), true)
    await until(async () => await editor.count() === 0)
    assert.equal(state.writes.filter((write) => write.action === 'edit').length, 1)
    assert.match(await page.locator('article').last().innerText(), /Bài viết đã sửa/)
    assert.match(await page.locator('article').last().innerText(), /1 bình luận/)
    state.failAction = true
    await trigger.click()
    await page.getByRole('menuitem', { name: 'Chỉnh sửa bài viết', exact: true }).click()
    await editor.getByRole('textbox').fill('Bài viết không lưu được')
    await editor.getByRole('button', { name: 'Lưu', exact: true }).click()
    await until(async () => !await editor.getByRole('button', { name: 'Lưu', exact: true }).isDisabled())
    assert.equal(await editor.getByRole('textbox').inputValue(), 'Bài viết không lưu được')
    assert.equal(await page.getByRole('status').filter({ hasText: 'Không thể lưu bài viết thử nghiệm.' }).count(), 1)
    await page.keyboard.press('Escape')
    state.failAction = false
    await page.getByRole('button', { name: 'Chia sẻ', exact: true }).first().click()
    const share = page.getByRole('dialog', { name: 'Chia sẻ', exact: true })
    await share.waitFor()
    await page.keyboard.press('Escape')
    assert.equal(await share.count(), 0)
  })
  await check('pending dialogs keep Tab and Shift+Tab inside and recover focus after success or error', async () => {
    state.shareDelay = 900
    const trigger = page.getByRole('button', { name: 'Chia sẻ', exact: true }).first()
    const dialog = page.getByRole('dialog', { name: 'Chia sẻ', exact: true })
    const submit = dialog.getByRole('button', { name: 'Chia sẻ', exact: true })
    const verifyPendingFocus = async () => {
      await until(async () => await dialog.getByRole('button', { name: 'Đang chia sẻ…', exact: true }).isDisabled())
      assert.equal(await dialog.locator('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled])').count(), 0)
      await page.keyboard.press('Tab')
      assert.equal(await dialog.evaluate((element) => element === document.activeElement), true)
      await page.keyboard.press('Shift+Tab')
      assert.equal(await dialog.evaluate((element) => element === document.activeElement), true)
    }
    await trigger.click()
    await submit.click()
    await verifyPendingFocus()
    await until(async () => await dialog.count() === 0)
    assert.equal(await trigger.evaluate((element) => element === document.activeElement), true)
    assert.equal(state.post.shareCount, 1)

    state.failShare = true
    await trigger.click()
    await submit.click()
    await verifyPendingFocus()
    await until(async () => await dialog.getByRole('button', { name: 'Chia sẻ', exact: true }).isEnabled())
    assert.equal(await dialog.getByRole('alert').innerText(), 'Không thể chia sẻ bài viết thử nghiệm.')
    await page.keyboard.press('Tab')
    assert.equal(await dialog.getByRole('button', { name: 'Đóng chia sẻ', exact: true }).evaluate((element) => element === document.activeElement), true)
    await page.keyboard.press('Shift+Tab')
    assert.equal(await submit.evaluate((element) => element === document.activeElement), true)
    await page.keyboard.press('Escape')
    assert.equal(await dialog.count(), 0)
    assert.equal(await trigger.evaluate((element) => element === document.activeElement), true)
    assert.equal(state.post.shareCount, 1)
    assert.equal(state.writes.filter((write) => write.action === 'share').length, 2)
    state.failShare = false
  })
  await context.close()

  const reporting = await browser.newContext({ viewport: { width: 1280, height: 900 } })
  await postFixtures(reporting, { authorUserId: '00000000-0000-0000-0000-000000000009' })
  const reportPage = await reporting.newPage()
  trackErrors(reportPage)
  await reportPage.goto(`${baseUrl}/posts/${postId}`)
  await check('report action keeps its modal usable after the post menu closes', async () => {
    const trigger = reportPage.getByRole('button', { name: 'Tùy chọn khác', exact: true })
    await trigger.click()
    await reportPage.getByRole('menuitem', { name: 'Báo cáo', exact: true }).click()
    const dialog = reportPage.getByRole('dialog', { name: 'Báo cáo bài viết', exact: true })
    await dialog.waitFor()
    assert.equal(await trigger.getAttribute('aria-expanded'), 'false')
    await dialog.getByRole('combobox').selectOption('spam')
    assert.equal(await dialog.count(), 1)
    await reportPage.keyboard.press('Escape')
    assert.equal(await dialog.count(), 0)
    assert.equal(await trigger.evaluate((element) => element === document.activeElement), true)
  })
  await reporting.close()

  const switchSession = (page, userId, accessToken) => page.evaluate(({ userId, accessToken }) => {
    const session = JSON.parse(localStorage.getItem('fookbase.session'))
    session.user = { ...session.user, id: userId }
    session.accessToken = accessToken
    localStorage.setItem('fookbase.session', JSON.stringify(session))
    localStorage.setItem('fookbase.accessToken', accessToken)
    window.dispatchEvent(new Event('fookbase.auth-session-changed'))
  }, { userId, accessToken })
  const switching = await browser.newContext({ viewport: { width: 1366, height: 900 } })
  const switchingState = await postFixtures(switching)
  switchingState.reactionDelay = 1_200
  const switchingPage = await switching.newPage()
  trackErrors(switchingPage)
  await switchingPage.goto(`${baseUrl}/posts/${postId}`)
  const switchingReaction = switchingPage.locator('[data-post-reaction]').first()
  await switchingReaction.waitFor()
  await check('switching accounts cancels the old viewer queued reaction and suppresses irrelevant toast', async () => {
    await switchingReaction.focus()
    await switchingReaction.press('ArrowDown')
    await switchingPage.getByRole('menuitemradio', { name: 'Yêu thích', exact: true }).click()
    await until(() => switchingState.writes.length === 1)
    await switchingReaction.focus()
    await switchingReaction.press('ArrowDown')
    await switchingPage.getByRole('menuitemradio', { name: 'Wow', exact: true }).click()
    assert.match(await switchingReaction.innerText(), /Wow/)
    await switchSession(switchingPage, '00000000-0000-0000-0000-000000000008', 'browser-fixture-other-viewer')
    await until(async () => await switchingReaction.getAttribute('aria-pressed') === 'false')
    await until(() => switchingState.reactionResponses === 1)
    await switchingPage.waitForTimeout(150)
    assert.deepEqual(switchingState.writes.map((write) => write.type), ['love'])
    assert.equal(switchingState.writes[0].authorization, 'Bearer browser-fixture')
    assert.equal(await switchingPage.getByRole('status').count(), 0)
    assert.equal(await switchingReaction.getAttribute('aria-pressed'), 'false')
    await switchSession(switchingPage, viewerId, 'browser-fixture-returned-viewer')
    await until(async () => /Yêu thích/.test(await switchingReaction.innerText()))
    assert.equal(await switchingPage.getByRole('button', { name: 'Xem 4 cảm xúc', exact: true }).count(), 1)
    assert.equal(switchingState.writes.length, 1)
  })
  await switching.close()

  const refreshing = await browser.newContext({ viewport: { width: 1366, height: 900 } })
  const refreshingState = await postFixtures(refreshing)
  refreshingState.reactionDelay = 1_000
  const refreshingPage = await refreshing.newPage()
  trackErrors(refreshingPage)
  await refreshingPage.goto(`${baseUrl}/posts/${postId}`)
  const refreshingReaction = refreshingPage.locator('[data-post-reaction]').first()
  await refreshingReaction.waitFor()
  await check('refreshing a token for the same viewer preserves the queued reaction', async () => {
    await refreshingReaction.focus()
    await refreshingReaction.press('ArrowDown')
    await refreshingPage.getByRole('menuitemradio', { name: 'Yêu thích', exact: true }).click()
    await until(() => refreshingState.writes.length === 1)
    await refreshingReaction.focus()
    await refreshingReaction.press('ArrowDown')
    await refreshingPage.getByRole('menuitemradio', { name: 'Wow', exact: true }).click()
    await switchSession(refreshingPage, viewerId, 'browser-fixture-refreshed')
    await until(() => refreshingState.reactionResponses === 2 && refreshingState.post.viewerReaction === 'wow')
    assert.deepEqual(refreshingState.writes.map((write) => write.type), ['love', 'wow'])
    assert.deepEqual(refreshingState.writes.map((write) => write.authorization), ['Bearer browser-fixture', 'Bearer browser-fixture-refreshed'])
    assert.match(await refreshingReaction.innerText(), /Wow/)
    assert.equal(await refreshingPage.getByRole('button', { name: 'Xem 4 cảm xúc', exact: true }).count(), 1)
    assert.equal(await refreshingPage.getByRole('status').count(), 0)
  })
  await refreshing.close()

  const racing = await browser.newContext({ viewport: { width: 1366, height: 1000 } })
  const racingState = await postFixtures(racing)
  const racingPage = await racing.newPage()
  trackErrors(racingPage)
  await racingPage.goto(`${baseUrl}/posts/${postId}`)
  await racingPage.locator('[data-post-reaction]').first().waitFor()
  racingState.comments = Array.from({ length: 30 }, (_, index) => ({
    id: `00000000-0000-0000-0000-${String(index + 200).padStart(12, '0')}`,
    postId, authorUserId: viewerId, parentCommentId: null, content: `Bình luận đã có ${index + 1}`,
    createdAtUtc: `2026-01-01T00:00:${String(index).padStart(2, '0')}Z`, updatedAtUtc: null,
    reactionCounts: {}, viewerReaction: null, author: { userId: viewerId, username: 'explorer', displayName: 'Người kiểm tra', avatarUrl: null },
  }))
  racingState.post = { ...racingState.post, commentCount: 30 }
  racingState.commentsReadDelay = 800
  await check('posting while a stale partial comment page loads reconciles the count and preserves pagination', async () => {
    await racingPage.getByRole('button', { name: 'Bình luận', exact: true }).first().click()
    const dialog = racingPage.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    await dialog.getByRole('textbox', { name: 'Viết bình luận', exact: true }).fill('Bình luận khi danh sách còn tải')
    await dialog.getByRole('button', { name: 'Gửi', exact: true }).click()
    await until(() => racingState.comments.length === 31)
    await until(async () => /31 bình luận/.test(await racingPage.locator('article').last().innerText()))
    assert.equal(await dialog.locator('[data-comment-id]').count(), 21)
    await dialog.getByRole('button', { name: 'Tải thêm bình luận', exact: true }).click()
    await until(async () => await dialog.locator('[data-comment-id]').count() === 31)
    assert.equal(await dialog.getByRole('button', { name: 'Tải thêm bình luận', exact: true }).count(), 0)
    assert.equal(await dialog.getByText('Bình luận khi danh sách còn tải', { exact: true }).count(), 1)
  })
  await racing.close()

  const duplicates = await browser.newContext({ viewport: { width: 1366, height: 1000 } })
  const sharedState = await postFixtures(duplicates)
  const feedPage = await duplicates.newPage()
  trackErrors(feedPage)
  await feedPage.goto(`${baseUrl}/feed`)
  await until(async () => await feedPage.locator('[data-post-reaction]').count() === 3)
  const directReaction = feedPage.locator('[data-post-reaction]').nth(0)
  const sharedReaction = feedPage.locator('[data-post-reaction]').nth(1)
  const otherReaction = feedPage.locator('[data-post-reaction]').nth(2)
  const directCard = directReaction.locator('xpath=ancestor::article[1]')
  const sharedCard = sharedReaction.locator('xpath=ancestor::article[1]')
  const feedReads = sharedState.feedReads
  await check('original and shared cards update together while another post and feed stay unchanged', async () => {
    await directReaction.click()
    assert.equal(await sharedReaction.getAttribute('aria-pressed'), 'true')
    assert.equal(await directCard.getByRole('button', { name: 'Xem 4 cảm xúc', exact: true }).count(), 1)
    assert.equal(await sharedCard.getByRole('button', { name: 'Xem 4 cảm xúc', exact: true }).count(), 1)
    assert.equal(await otherReaction.getAttribute('aria-pressed'), 'false')
    await until(() => sharedState.post.viewerReaction === 'like')
    await sharedReaction.click()
    assert.equal(await directReaction.getAttribute('aria-pressed'), 'false')
    await until(() => sharedState.post.viewerReaction === null)
    assert.equal(sharedState.feedReads, feedReads)
  })
  await check('comment list and count are shared across both cards without a feed refetch', async () => {
    await directCard.getByRole('button', { name: 'Bình luận', exact: true }).click()
    let dialog = feedPage.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    await dialog.getByRole('textbox', { name: 'Viết bình luận', exact: true }).fill('Hiển thị ở cả hai vị trí')
    await dialog.getByRole('button', { name: 'Gửi', exact: true }).dblclick()
    assert.match(await directCard.innerText(), /1 bình luận/)
    assert.match(await sharedCard.innerText(), /1 bình luận/)
    await feedPage.getByRole('button', { name: 'Đóng bình luận', exact: true }).click()
    await until(() => sharedState.comments.length === 1)
    await sharedCard.getByRole('button', { name: 'Bình luận', exact: true }).click()
    dialog = feedPage.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    assert.equal(await dialog.locator('[data-comment-id]').count(), 1)
    assert.equal(sharedState.writes.filter((write) => write.action === 'comment').length, 1)
    assert.equal(sharedState.feedReads, feedReads)
    await feedPage.keyboard.press('Escape')
  })
  await check('a reaction survives component unmount and remount during a pending request', async () => {
    sharedState.reactionDelay = 800
    await directReaction.click()
    await feedPage.locator('a[href="/saved"]').first().click()
    await until(async () => !await feedPage.locator('[data-post-reaction]').count())
    await until(() => sharedState.post.viewerReaction === 'like')
    await feedPage.locator('a[href="/feed"]').first().click()
    await until(async () => await feedPage.locator('[data-post-reaction]').count() === 3)
    assert.equal(await directReaction.getAttribute('aria-pressed'), 'true')
    assert.equal(await sharedReaction.getAttribute('aria-pressed'), 'true')
    assert.match(await directCard.innerText(), /1 bình luận/)
  })
  await check('a comment survives unmount without duplicate rows or lost counters on return', async () => {
    sharedState.commentDelay = 700
    await directCard.getByRole('button', { name: 'Bình luận', exact: true }).click()
    const dialog = feedPage.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    await dialog.getByRole('textbox', { name: 'Viết bình luận', exact: true }).fill('Bình luận khi rời trang')
    await dialog.getByRole('button', { name: 'Gửi', exact: true }).click()
    await feedPage.keyboard.press('Escape')
    await feedPage.locator('a[href="/saved"]').first().click()
    await until(async () => !await feedPage.locator('[data-post-reaction]').count())
    await until(() => sharedState.comments.length === 2)
    await feedPage.locator('a[href="/feed"]').first().click()
    await until(async () => await feedPage.locator('[data-post-reaction]').count() === 3)
    assert.match(await directCard.innerText(), /2 bình luận/)
    assert.match(await sharedCard.innerText(), /2 bình luận/)
    await sharedCard.getByRole('button', { name: 'Bình luận', exact: true }).click()
    const reopened = feedPage.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    assert.equal(await reopened.locator('[data-comment-id]').count(), 2)
    assert.equal(await reopened.locator('[data-comment-id][aria-busy="true"]').count(), 0)
    await feedPage.keyboard.press('Escape')
  })
  await duplicates.close()

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  const mobileState = await postFixtures(mobile)
  const phone = await mobile.newPage()
  trackErrors(phone)
  await phone.goto(`${baseUrl}/posts/${postId}`)
  const mobileReaction = phone.locator('[data-post-reaction]').first()
  await mobileReaction.waitFor()
  await check('mobile long press opens six reactions and preserves scroll gestures', async () => {
    await mobileReaction.dispatchEvent('pointerdown', { pointerType: 'touch', clientX: 80, clientY: 230 })
    await mobileReaction.dispatchEvent('pointermove', { pointerType: 'touch', clientX: 80, clientY: 260 })
    await phone.waitForTimeout(500)
    assert.equal(await mobileReaction.getAttribute('aria-expanded'), 'false')
    await mobileReaction.dispatchEvent('pointercancel', { pointerType: 'touch' })
    await mobileReaction.dispatchEvent('pointerdown', { pointerType: 'touch', clientX: 80, clientY: 230 })
    await phone.waitForTimeout(470)
    await mobileReaction.dispatchEvent('pointerup', { pointerType: 'touch' })
    await mobileReaction.dispatchEvent('click')
    const menu = phone.getByRole('menu', { name: 'Chọn cảm xúc', exact: true })
    await menu.waitFor()
    const popup = await menu.boundingBox()
    assert.ok(popup.x >= 0 && popup.x + popup.width <= 390)
    await phone.getByRole('menuitemradio', { name: 'Yêu thích', exact: true }).tap()
    await until(() => mobileState.post.viewerReaction === 'love')
    assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  })
  await check('mobile comments, dropdown, resize and light theme remain usable', async () => {
    await phone.getByRole('button', { name: 'Bình luận', exact: true }).first().tap()
    const dialog = phone.getByRole('dialog', { name: 'Bài viết của Người kiểm tra', exact: true })
    await dialog.getByRole('textbox', { name: 'Viết bình luận', exact: true }).fill('Bình luận trên điện thoại')
    await dialog.getByRole('button', { name: 'Gửi', exact: true }).tap()
    await until(() => mobileState.comments.length === 1)
    await phone.getByRole('button', { name: 'Đóng bình luận', exact: true }).tap()
    const trigger = phone.getByRole('button', { name: 'Tùy chọn khác', exact: true })
    await trigger.tap()
    const menu = phone.getByRole('menu', { name: 'Tùy chọn khác', exact: true })
    await menu.waitFor()
    await phone.setViewportSize({ width: 320, height: 740 })
    await phone.waitForTimeout(200)
    const bounds = await menu.boundingBox()
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 320)
    await phone.mouse.click(5, 600)
    await phone.evaluate(() => { document.documentElement.dataset.theme = 'light' })
    await trigger.tap()
    assert.equal(await menu.evaluate((element) => getComputedStyle(element).backgroundColor), 'rgb(255, 255, 255)')
    assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  })
  await mobile.close()
  assert.deepEqual(failures, [])
  console.log(`${passed.length} browser checks passed; no unexpected console/page errors.`)
} finally {
  await browser.close()
}
