import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { eventsApi, type Event, type EventInvitation } from '../../api/events'
import { ApiError } from '../../api/client'

function EventCard({ event }: { event: Event }) { return <Link to={`/events/${event.id}`} className="block rounded-xl border border-border bg-surface p-4 no-underline hover:bg-surface-2"><div className="flex gap-3">{event.coverUrl ? <img src={event.coverUrl} alt="" className="h-16 w-16 rounded-lg object-cover" /> : <div className="grid h-16 w-16 place-items-center rounded-lg bg-primary/15 text-2xl">📅</div>}<div><h2 className="font-heading font-bold text-text">{event.name}</h2><p className="mt-1 text-sm text-text-muted">{new Date(event.startsAtUtc).toLocaleString()} · {event.displayHost.name}</p><p className="mt-1 text-xs text-text-muted">{event.goingCount} going · {event.interestedCount} interested · {event.privacy}</p></div></div></Link> }
export default function EventsPage() { const [upcoming,setUpcoming]=useState<Event[]>([]),[discover,setDiscover]=useState<Event[]>([]),[invites,setInvites]=useState<EventInvitation[]>([]),[mine,setMine]=useState<Event[]>([]),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true)
  const load=useCallback(async()=>{setLoading(true);try{const [a,b,c,d]=await Promise.all([eventsApi.upcoming(),eventsApi.discover(),eventsApi.invitations(),eventsApi.mine()]);setUpcoming(a.items);setDiscover(b.items);setInvites(c.items);setMine(d.items)}catch(e){setError(e instanceof ApiError?e.message:'Unable to load events.')}finally{setLoading(false)}},[])
  useEffect(()=>{const timeoutId=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timeoutId)},[load]); const respond=async(i:EventInvitation,accept:boolean)=>{try{if(accept)await eventsApi.acceptInvite(i.id);else await eventsApi.declineInvite(i.id);await load()}catch(e){setError(e instanceof ApiError?e.message:'Unable to update invitation.')}}
  return <main className="mx-auto min-h-screen w-full max-w-6xl px-3 py-5 sm:px-5"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Community</p><h1 className="font-heading text-3xl font-bold text-text">Events</h1></div><Link to="/events/create" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white no-underline">Create event</Link></div>{error&&<p className="mb-4 rounded-lg bg-red-500/10 p-3 text-red-400">{error}</p>}{loading?<p className="text-text-muted">Loading events…</p>:<div className="grid gap-6 lg:grid-cols-2"><section><h2 className="mb-3 font-heading text-xl font-bold text-text">Upcoming</h2><div className="grid gap-3">{upcoming.length?upcoming.map(x=><EventCard key={x.id} event={x}/>):<p className="text-sm text-text-muted">No upcoming events.</p>}</div></section><section><h2 className="mb-3 font-heading text-xl font-bold text-text">Invitations</h2><div className="grid gap-3">{invites.length?invites.map(x=>x.event&&<div key={x.id} className="rounded-xl border border-border bg-surface p-4"><EventCard event={x.event}/><div className="mt-3 flex gap-2"><button onClick={()=>void respond(x,true)} className="rounded bg-primary px-3 py-1.5 text-sm text-white">Accept</button><button onClick={()=>void respond(x,false)} className="rounded border border-border px-3 py-1.5 text-sm text-text">Decline</button></div></div>):<p className="text-sm text-text-muted">No pending invitations.</p>}</div></section><section><h2 className="mb-3 font-heading text-xl font-bold text-text">Discover</h2><div className="grid gap-3">{discover.map(x=><EventCard key={x.id} event={x}/>)}</div></section><section><h2 className="mb-3 font-heading text-xl font-bold text-text">My events</h2><div className="grid gap-3">{mine.length?mine.map(x=><EventCard key={x.id} event={x}/>):<p className="text-sm text-text-muted">You are not managing any events.</p>}</div></section></div>}</main> }
