import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { eventsApi, type Event, type EventInvitation } from '../../api/events'
import { ApiError } from '../../api/client'
import { Mascot } from 'page-mascot'

function EventCard({ event }: { event: Event }) { return <Link to={`/events/${event.id}`} className="block rounded-xl border border-border bg-surface p-4 no-underline hover:bg-surface-2"><div className="flex gap-3">{event.coverUrl ? <img src={event.coverUrl} alt="" loading="lazy" className="h-16 w-16 rounded-lg object-cover" /> : <div className="grid h-16 w-16 place-items-center rounded-lg bg-primary/15 text-2xl">📅</div>}<div><h2 className="font-heading font-bold text-text">{event.name}</h2><p className="mt-1 text-sm text-text-muted">{new Date(event.startsAtUtc).toLocaleString()} · {event.displayHost.name}</p><p className="mt-1 text-xs text-text-muted">{event.goingCount} sẽ tham gia · {event.interestedCount} quan tâm · {event.privacy}</p></div></div></Link> }
export default function EventsPage() {
  const [upcoming, setUpcoming] = useState<Event[]>([]), [discover, setDiscover] = useState<Event[]>([]), [invites, setInvites] = useState<EventInvitation[]>([]), [mine, setMine] = useState<Event[]>([]), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const [a, b, c, d] = await Promise.all([eventsApi.upcoming(), eventsApi.discover(), eventsApi.invitations(), eventsApi.mine()]); setUpcoming(a.items); setDiscover(b.items); setInvites(c.items); setMine(d.items) } catch (e) { setError(e instanceof ApiError ? e.message : 'Không thể tải sự kiện.') } finally { setLoading(false) } }, [])
  useEffect(() => { const timeoutId = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timeoutId) }, [load]); const respond = async (i: EventInvitation, accept: boolean) => { try { if (accept) await eventsApi.acceptInvite(i.id); else await eventsApi.declineInvite(i.id); await load() } catch (e) { setError(e instanceof ApiError ? e.message : 'Unable to update invitation.') } }
  return <main className="mx-auto min-h-screen w-full max-w-6xl px-3 py-5 sm:px-5"><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-4"><Mascot directions="/mascots/lantern-directions.webp" reactions="/mascots/lantern-reactions.webp" size={72} label="Event lantern mascot" /><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Cộng đồng</p><h1 className="font-heading text-3xl font-bold text-text">Sự kiện</h1></div></div><Link to="/events/create" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white no-underline">Tạo sự kiện</Link></div>{error && <p className="mb-4 rounded-lg bg-red-500/10 p-3 text-red-400">{error}</p>}{loading ? <p className="text-text-muted">Đang tải sự kiện…</p> : <div className="grid gap-6 lg:grid-cols-2"><section><h2 className="mb-3 font-heading text-xl font-bold text-text">Sắp diễn ra</h2><div className="grid gap-3">{upcoming.length ? upcoming.map(x => <EventCard key={x.id} event={x} />) : <p className="text-sm text-text-muted">Chưa có sự kiện sắp diễn ra.</p>}</div></section><section><h2 className="mb-3 font-heading text-xl font-bold text-text">Lời mời</h2><div className="grid gap-3">{invites.length ? invites.map(x => x.event && <div key={x.id} className="rounded-xl border border-border bg-surface p-4"><EventCard event={x.event} /><div className="mt-3 flex gap-2"><button onClick={() => void respond(x, true)} className="rounded bg-primary px-3 py-1.5 text-sm text-white">Chấp nhận</button><button onClick={() => void respond(x, false)} className="rounded border border-border px-3 py-1.5 text-sm text-text">Từ chối</button></div></div>) : <p className="text-sm text-text-muted">Chưa có lời mời đang chờ.</p>}</div></section><section><h2 className="mb-3 font-heading text-xl font-bold text-text">Khám phá</h2><div className="grid gap-3">{discover.map(x => <EventCard key={x.id} event={x} />)}</div></section><section><h2 className="mb-3 font-heading text-xl font-bold text-text">Sự kiện của bạn</h2><div className="grid gap-3">{mine.length ? mine.map(x => <EventCard key={x.id} event={x} />) : <p className="text-sm text-text-muted">Bạn chưa quản lý sự kiện nào.</p>}</div></section></div>}</main>
}
