import { useCallback, useEffect, useMemo, useState } from 'react'
import { PreferencesContext } from './context'
import type { AppLanguage, AppTheme, PreferencesContextValue } from './context'

const preferencesStorageKey = 'fookbase.preferences'

const messages = {
  en: {
    home: 'Home',
    feed: 'Feed',
    explore: 'Explore',
    messages: 'Messages',
    groups: 'Groups',
    games: 'Games',
    profile: 'Profile',
    searchFookbase: 'Search Fookbase',
    signOut: 'Sign out',
    notifications: 'Notifications',
    messageNotifications: 'Message notifications',
    openMessages: 'Open messages',
    allCaughtUp: 'You are all caught up.',
    newFriendRequest: 'New friend request',
    friendRequestAccepted: 'Friend request accepted',
    viewProfile: 'View profile',
    newMessage: 'New message',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
    language: 'Language',
    appearance: 'Appearance',
    english: 'English',
    vietnamese: 'Tiếng Việt',
    socialSpace: 'YOUR SOCIAL SPACE',
    quieterCorner: 'A quieter corner of the internet.',
    socialDescription: 'Keep up with your people, share what matters, and turn everyday moments into conversations.',
    shareWorld: 'Share your world',
    shareWorldDescription: 'Posts, reactions, and conversations that feel close.',
    stayConnected: 'Stay connected',
    stayConnectedDescription: 'Private messages and live updates with your friends.',
    madeForCircle: 'Made for your circle',
    madeForCircleDescription: 'Your feed is shaped around the people you know.',
    socialSimplified: 'SOCIAL, SIMPLIFIED',
    emailVerification: 'EMAIL VERIFICATION',
    resetPassword: 'RESET PASSWORD',
    accountRecovery: 'ACCOUNT RECOVERY',
    joinFookbase: 'JOIN FOOKBASE',
    welcomeBack: 'WELCOME BACK',
    verifyEmailTitle: 'Verify your email.',
    newPasswordTitle: 'Choose a new password.',
    resetPasswordTitle: 'Reset your password.',
    createSpaceTitle: 'Create your space.',
    signInSpaceTitle: 'Sign in to your space.',
    verifyEmailDescription: 'We are confirming the email address linked to your Fookbase account.',
    newPasswordDescription: 'Use a strong password you do not use elsewhere.',
    resetPasswordDescription: 'Enter your email and we will send a secure reset link.',
    createSpaceDescription: 'Set up your account in a moment and start connecting.',
    signInSpaceDescription: 'Enter your details to continue where you left off.',
    registrationVerification: 'VERIFY YOUR ACCOUNT',
    registrationVerificationTitle: 'Enter your verification code.',
    registrationVerificationDescription: 'We sent a six-digit code to your email address or phone number.',
    verificationCode: 'Verification code',
    verifyAndCreateAccount: 'Verify and create account',
    resendCode: 'Resend code',
    editRegistrationDetails: 'Edit registration details',
    emailAddress: 'Email address',
    mobileOrEmail: 'Mobile number or email',
    mobileOrEmailPlaceholder: 'you@example.com or 0912 345 678',
    firstName: 'First name',
    lastName: 'Last name',
    dateOfBirth: 'Date of birth',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    gender: 'Gender',
    female: 'Female',
    male: 'Male',
    otherGender: 'Other',
    preferNotToSay: 'Prefer not to say',
    username: 'Username',
    chooseUsername: 'Choose a username',
    password: 'Password',
    passwordAtLeastEight: 'At least 8 characters',
    yourPassword: 'Your password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    show: 'SHOW',
    hide: 'HIDE',
    confirmPassword: 'Confirm new password',
    repeatPassword: 'Repeat your new password',
    respectfulUse: 'By creating an account, you agree to use Fookbase respectfully and keep your login details private.',
    pleaseWait: 'Please wait...',
    sendResetLink: 'Send reset link',
    resetPasswordAction: 'Reset password',
    createAccount: 'Create account',
    signIn: 'Sign in',
    backToSignIn: 'Back to sign in',
    forgotPassword: 'Forgot password?',
    or: 'OR',
    alreadyHaveAccount: 'I already have an account',
    createNewAccount: 'Create a new account',
    invalidVerificationLink: 'The verification link is invalid.',
    verifyingEmail: 'Verifying your email...',
    emailVerified: 'Your email has been verified. You can continue using Fookbase.',
    unableVerifyEmail: 'Unable to verify email from this link.',
    unableVerify: 'Unable to verify email.',
    unableAuthenticate: 'Unable to authenticate.',
    continueWithGoogle: 'Continue with Google',
    googleCompletionFailed: 'Unable to complete Google sign-in.',
    confirmGooglePassword: 'Confirm your Fookbase password for {email}.',
    openExternalBrowserGoogle: 'Open this page in Chrome or Safari to sign in with Google.',
    resetLinkSent: 'If this email has an account, we sent a password-reset link.',
    resetCodeSent: 'If this phone number has an account, we sent a verification code.',
    passwordReset: 'Your password has been reset. You can sign in with the new password.',
    loading: 'Loading...', loadingFeed: 'Loading feed...', noPostsYet: 'No posts yet.', loadMorePosts: 'Load more posts',
    following: 'Following', follow: 'Follow', followers: 'followers', followingCount: 'following', followsYou: 'Follows you', startedFollowingYou: 'started following you.', feedModes: 'Feed mode', unableLoadFeed: 'Unable to load your feed.',
    homeFeedDescription: 'From your friends, Groups and Pages, with occasional suggested Reels.',
    followingFeedDescription: 'Your friends, Groups and Pages, newest first.',
    feedChangedRefresh: 'Your feed has changed. Refresh to continue.', inGroup: 'in',
    suggestedReel: 'Suggested Reel', openReel: 'Open Reel', unableLoadReelPreview: 'Preview unavailable. Open the Reel to watch.',
    peopleYouMayKnow: 'People you may know', peopleYouMayKnowDescription: 'Suggestions are based on people you may know.', view: 'View', noSuggestionsYet: 'No suggestions yet.', remove: 'Remove', requestSent: 'Request sent', friendRequestReceived: 'Friend request received',
    terms: 'Terms', privacy: 'Privacy', cookies: 'Cookies', adsInfo: 'Ads info', more: 'More',
    defaultPostPrivacy: 'Default audience for posts', friendRequestPolicy: 'Who can send friend requests',
    friendListVisibility: 'Who can see your friend list', followListVisibility: 'Who can see your following list',
    onlyMe: 'Only me', everyone: 'Everyone', friendsOfFriends: 'Friends of friends',
    save: 'Save', privacySettingsSaved: 'Privacy settings saved.', privacyMascot: 'Privacy raccoon mascot',
    onlyJpegPngWebpMp4Webm: 'Only JPEG, PNG, WebP, MP4 and WebM are supported.', fileTooLarge: 'The file is too large.',
    maxAttachments: 'A post can have at most', attachments: 'attachments.', onlyFirstAttachments: 'Only the first', attachmentsWereAdded: 'attachments were added.',
    unableCreatePost: 'Unable to create post.', posts: 'Posts', whatsOnMind: "What's on your mind", video: 'Video', photoVideo: 'Photo/video',
    feelingActivity: 'Feeling/activity', public: 'Public', discardPost: 'Discard post?', close: 'Close', attachment: 'Attachment',
    removeAttachment: 'Remove attachment', posting: 'Posting...', post: 'Post',
    unableLoadComments: 'Unable to load comments.', unableUpdateReaction: 'Unable to update reaction.', unableCreateComment: 'Unable to add comment.',
    editCommentPrompt: 'Edit comment', unableEditComment: 'Unable to edit comment.', deleteCommentConfirm: 'Delete this comment?',
    unableDeleteComment: 'Unable to delete comment.', editPostPrompt: 'Edit post', unableEditPost: 'Unable to edit post.',
    deletePostConfirm: 'Delete this post?', unableDeletePost: 'Unable to delete post.', user: 'User', edit: 'Edit', delete: 'Delete',
    browserNoVideo: 'Your browser does not support video playback.', postAttachment: 'Post attachment', likes: 'likes', comments: 'comments',
    liked: 'Liked', like: 'Like', comment: 'Comment', writeComment: 'Write a comment', send: 'Send', moreOptions: 'More options',
    shares: 'shares', shared: 'Shared', share: 'Share',
    unableSearchUsers: 'Unable to search users.', unableSearchPosts: 'Unable to search posts.', unableUpdateRelationship: 'Unable to update relationship.',
    friends: 'Friends', cancelRequest: 'Cancel request', acceptRequest: 'Accept request', unavailable: 'Unavailable', sending: 'Sending...',
    addFriend: 'Add friend', searchPeoplePosts: 'Search people and posts...', clearSearch: 'Clear search',
    latestPosts: 'Latest posts', searchingPosts: 'Searching posts...', noPostsMatching: 'No posts found matching', noVisiblePostsYet: 'No visible posts yet.',
    viewAuthor: 'View author', reactions: 'reactions', people: 'People', peopleToDiscover: 'People to discover', searchingUsers: 'Searching users...',
    noPeopleMatching: 'No people found matching', noUsersDiscover: 'No users to discover yet.', loadMorePeople: 'Load more people',
    unableLoadConversations: 'Unable to load conversations.', unableLoadMessages: 'Unable to load messages.', unableCreateConversation: 'Unable to start a conversation.',
    unableSendMessage: 'Unable to send message.', searchMessages: 'Search messages...', findPerson: 'Find a person...',
    loadingConversations: 'Loading conversations...', noConversations: 'No conversations yet.', unknownUser: 'Unknown user', startConversation: 'Start a conversation',
    selectConversation: 'Select a conversation or create a new one.', refresh: 'Refresh', seen: 'Seen', isTyping: 'is typing',
    noMessagesSayHello: 'No messages yet. Say hello.', message: 'Message...', sendMessage: 'Send message', now: 'now',
    quickBreak: 'Take a quick break', gamesDescription: 'Play a round of Tic-tac-toe without leaving Fookbase.',
    ticTacToe: 'Tic-tac-toe', youPlayX: 'You play X. The computer plays O.', youWonRound: 'You won this round!', computerWonRound: 'The computer won this round.',
    drawRound: 'It is a draw.', yourTurn: 'Your turn — choose a square.', computerThinking: 'Computer is thinking…', square: 'Square',
    newRound: 'New round', resetScore: 'Reset score', scoreboard: 'Scoreboard', you: 'You', draws: 'Draws', computer: 'Computer',
    howToPlay: 'How to play', gameRuleOne: 'Choose an empty square to place an X.', gameRuleTwo: 'Get three marks in a row, column, or diagonal.',
    gameRuleThree: 'Start a new round anytime and keep your score.',
    unableLoadProfile: 'Unable to load profile.', accept: 'Accept', decline: 'Decline', unfriend: 'Unfriend', unblock: 'Unblock',
    relationshipUnavailable: 'Relationship unavailable', loadingProfile: 'Loading profile...', noCityListed: 'No city listed', mutualFriends: 'mutual friends',
    block: 'Block', noVisiblePosts: 'No visible posts.',
    updateProfilePicture: 'Update profile picture', uploading: 'Uploading', editCoverPhoto: 'Edit cover photo', editProfile: 'Edit profile',
    accountSecurity: 'Account security', security: 'Security', cancel: 'Cancel', saveProfile: 'Save profile', managePasswordSecurity: 'Manage your password and email verification.',
    emailNotVerified: 'Your email has not been verified yet.', managePosts: 'Manage posts', loadingPosts: 'Loading posts...', intro: 'Intro', noBioYet: 'No bio yet.',
    editBio: 'Edit bio', livesIn: 'Lives in', joined: 'Joined', friendsCount: 'friends', editDetails: 'Edit details', photos: 'Photos',
    seeAllPhotos: 'See all photos', loadingPhotos: 'Loading photos...', noPhotosPosted: 'No photos posted yet.', seeAllFriends: 'See all friends',
    noFriendsYet: 'No friends yet.', about: 'About', overview: 'Overview', currentCity: 'Current City', memberSince: 'Member Since', bio: 'Bio',
    friendRequests: 'Friend requests', sentRequests: 'Sent requests', blockedUsers: 'Blocked users', updating: 'Updating...', friendsSince: 'Friends since',
    loadMoreFriends: 'Load more friends', photosFromPosts: 'Photos from your posts',
    notSet: 'Not set', displayName: 'Display name', currentPassword: 'Current password', newPassword: 'New password',
    confirmNewPassword: 'Confirm new password', saving: 'Saving...', changePassword: 'Change password', resendVerificationEmail: 'Resend verification email',
    passwordChanged: 'Your password has been changed. Other sessions have been signed out.', verificationResent: 'Verification email has been resent.',
    unableChangePassword: 'Unable to change password.', unableResendVerification: 'Unable to resend verification email.', unableUpdateProfile: 'Unable to update profile.',
    unableLoadFriends: 'Unable to load friend data.', unableLoadMoreFriends: 'Unable to load more friends.', unableUpdateProfilePhoto: 'Unable to update profile picture.',
    unableLoadPosts: 'Unable to load posts.',
    loadMoreComments: 'Load more comments',
    loadMoreConversations: 'Load more conversations', loadMoreMessages: 'Load more messages',
    invalidProfilePhoto: 'Only JPEG, PNG or WebP images up to 20 MB are supported.',
    retry: 'Retry',
    unableSendReport: 'Unable to send report.', reported: 'Reported', report: 'Report', reportUser: 'Report user', reportPost: 'Report post',
    reportPrivate: 'Your report is private and will be reviewed by the Fookbase team.', closeReportDialog: 'Close report dialog', reason: 'Reason',
    spam: 'Spam', harassment: 'Harassment or bullying', hateSpeech: 'Hate speech', nudity: 'Nudity or sexual content', violence: 'Violence or dangerous content',
    scam: 'Scam or fraud', other: 'Other', additionalDetails: 'Additional details', optional: 'optional', tellUsWhatHappened: 'Tell us what happened', sendReport: 'Send report',
  },
  vi: {
    home: 'Trang chủ',
    feed: 'Bảng tin',
    explore: 'Khám phá',
    messages: 'Tin nhắn',
    groups: 'Nhóm',
    games: 'Trò chơi',
    profile: 'Trang cá nhân',
    searchFookbase: 'Tìm kiếm Fookbase',
    signOut: 'Đăng xuất',
    notifications: 'Thông báo',
    messageNotifications: 'Thông báo tin nhắn',
    openMessages: 'Mở tin nhắn',
    allCaughtUp: 'Bạn đã xem hết thông báo.',
    newFriendRequest: 'Lời mời kết bạn mới',
    friendRequestAccepted: 'Đã chấp nhận lời mời kết bạn',
    viewProfile: 'Xem trang cá nhân',
    newMessage: 'Tin nhắn mới',
    switchToLight: 'Chuyển sang giao diện sáng',
    switchToDark: 'Chuyển sang giao diện tối',
    language: 'Ngôn ngữ',
    appearance: 'Giao diện',
    english: 'English',
    vietnamese: 'Tiếng Việt',
    socialSpace: 'KHÔNG GIAN XÃ HỘI CỦA BẠN',
    quieterCorner: 'Một góc internet yên tĩnh hơn.',
    socialDescription: 'Kết nối với những người quan trọng, chia sẻ điều có ý nghĩa và biến khoảnh khắc thường ngày thành cuộc trò chuyện.',
    shareWorld: 'Chia sẻ thế giới của bạn',
    shareWorldDescription: 'Bài viết, cảm xúc và trò chuyện gần gũi.',
    stayConnected: 'Luôn kết nối',
    stayConnectedDescription: 'Tin nhắn riêng tư và cập nhật trực tiếp với bạn bè.',
    madeForCircle: 'Dành cho vòng kết nối của bạn',
    madeForCircleDescription: 'Bảng tin được tạo nên từ những người bạn biết.',
    socialSimplified: 'MẠNG XÃ HỘI, ĐƠN GIẢN HƠN',
    emailVerification: 'XÁC MINH EMAIL',
    resetPassword: 'ĐẶT LẠI MẬT KHẨU',
    accountRecovery: 'KHÔI PHỤC TÀI KHOẢN',
    joinFookbase: 'THAM GIA FOOKBASE',
    welcomeBack: 'CHÀO MỪNG TRỞ LẠI',
    verifyEmailTitle: 'Xác minh email của bạn.',
    newPasswordTitle: 'Chọn mật khẩu mới.',
    resetPasswordTitle: 'Đặt lại mật khẩu.',
    createSpaceTitle: 'Tạo không gian của bạn.',
    signInSpaceTitle: 'Đăng nhập vào không gian của bạn.',
    verifyEmailDescription: 'Chúng tôi đang xác nhận địa chỉ email được liên kết với tài khoản Fookbase của bạn.',
    newPasswordDescription: 'Hãy dùng mật khẩu mạnh mà bạn không sử dụng ở nơi khác.',
    resetPasswordDescription: 'Nhập email và chúng tôi sẽ gửi liên kết đặt lại an toàn.',
    createSpaceDescription: 'Thiết lập tài khoản trong giây lát và bắt đầu kết nối.',
    signInSpaceDescription: 'Nhập thông tin để tiếp tục từ nơi bạn đã dừng lại.',
    registrationVerification: 'XÁC NHẬN TÀI KHOẢN',
    registrationVerificationTitle: 'Nhập mã xác nhận.',
    registrationVerificationDescription: 'Chúng tôi đã gửi mã gồm sáu chữ số đến email hoặc số điện thoại của bạn.',
    verificationCode: 'Mã xác nhận',
    verifyAndCreateAccount: 'Xác nhận và tạo tài khoản',
    resendCode: 'Gửi lại mã',
    editRegistrationDetails: 'Sửa thông tin đăng ký',
    emailAddress: 'Địa chỉ email',
    mobileOrEmail: 'Số di động hoặc email',
    mobileOrEmailPlaceholder: 'you@example.com hoặc 0912 345 678',
    firstName: 'Tên',
    lastName: 'Họ',
    dateOfBirth: 'Ngày sinh',
    day: 'Ngày',
    month: 'Tháng',
    year: 'Năm',
    gender: 'Giới tính',
    female: 'Nữ',
    male: 'Nam',
    otherGender: 'Khác',
    preferNotToSay: 'Không muốn nêu',
    username: 'Tên người dùng',
    chooseUsername: 'Chọn tên người dùng',
    password: 'Mật khẩu',
    passwordAtLeastEight: 'Ít nhất 8 ký tự',
    yourPassword: 'Mật khẩu của bạn',
    showPassword: 'Hiện mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
    show: 'HIỆN',
    hide: 'ẨN',
    confirmPassword: 'Xác nhận mật khẩu mới',
    repeatPassword: 'Nhập lại mật khẩu mới',
    respectfulUse: 'Khi tạo tài khoản, bạn đồng ý sử dụng Fookbase một cách tôn trọng và bảo mật thông tin đăng nhập.',
    pleaseWait: 'Vui lòng chờ...',
    sendResetLink: 'Gửi liên kết đặt lại',
    resetPasswordAction: 'Đặt lại mật khẩu',
    createAccount: 'Tạo tài khoản',
    signIn: 'Đăng nhập',
    backToSignIn: 'Quay lại đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    or: 'HOẶC',
    alreadyHaveAccount: 'Tôi đã có tài khoản',
    createNewAccount: 'Tạo tài khoản mới',
    invalidVerificationLink: 'Liên kết xác minh không hợp lệ.',
    verifyingEmail: 'Đang xác minh email của bạn...',
    emailVerified: 'Email đã được xác minh. Bạn có thể tiếp tục sử dụng Fookbase.',
    unableVerifyEmail: 'Không thể xác minh email từ liên kết này.',
    unableVerify: 'Không thể xác minh email.',
    unableAuthenticate: 'Không thể xác thực.',
    continueWithGoogle: 'Tiếp tục với Google',
    googleCompletionFailed: 'Không thể hoàn tất đăng nhập Google.',
    confirmGooglePassword: 'Xác nhận mật khẩu Fookbase cho {email}.',
    openExternalBrowserGoogle: 'Hãy mở trang này bằng Chrome hoặc Safari để đăng nhập Google.',
    resetLinkSent: 'Nếu email này có tài khoản, chúng tôi đã gửi liên kết đặt lại mật khẩu.',
    resetCodeSent: 'Nếu số điện thoại này có tài khoản, chúng tôi đã gửi mã xác nhận.',
    passwordReset: 'Mật khẩu đã được đặt lại. Bạn có thể đăng nhập bằng mật khẩu mới.',
    loading: 'Đang tải...', loadingFeed: 'Đang tải bảng tin...', noPostsYet: 'Chưa có bài viết nào.', loadMorePosts: 'Tải thêm bài viết',
    following: 'Đang theo dõi', follow: 'Theo dõi', followers: 'người theo dõi', followingCount: 'đang theo dõi', followsYou: 'Theo dõi bạn', startedFollowingYou: 'đã bắt đầu theo dõi bạn.', feedModes: 'Chế độ bảng tin', unableLoadFeed: 'Không thể tải bảng tin.',
    homeFeedDescription: 'Từ bạn bè, Nhóm và Trang của bạn, cùng một số Reel gợi ý.',
    followingFeedDescription: 'Bạn bè, Nhóm và Trang của bạn, mới nhất trước.',
    feedChangedRefresh: 'Bảng tin đã thay đổi. Hãy làm mới để tiếp tục.', inGroup: 'trong',
    suggestedReel: 'Reel gợi ý', openReel: 'Mở Reel', unableLoadReelPreview: 'Không thể tải ảnh xem trước. Mở Reel để xem.',
    peopleYouMayKnow: 'Những người bạn có thể biết', peopleYouMayKnowDescription: 'Gợi ý dựa trên những người bạn có thể biết.', view: 'Xem', noSuggestionsYet: 'Chưa có gợi ý nào.', remove: 'Gỡ', requestSent: 'Đã gửi lời mời', friendRequestReceived: 'Đã nhận lời mời kết bạn',
    terms: 'Điều khoản', privacy: 'Quyền riêng tư', cookies: 'Cookie', adsInfo: 'Thông tin quảng cáo', more: 'Thêm',
    defaultPostPrivacy: 'Đối tượng mặc định cho bài viết', friendRequestPolicy: 'Ai có thể gửi lời mời kết bạn',
    friendListVisibility: 'Ai xem danh sách bạn bè', followListVisibility: 'Ai xem danh sách theo dõi',
    onlyMe: 'Chỉ mình tôi', everyone: 'Mọi người', friendsOfFriends: 'Bạn của bạn bè',
    save: 'Lưu', privacySettingsSaved: 'Đã lưu thiết lập riêng tư.', privacyMascot: 'Linh vật gấu mèo quyền riêng tư',
    onlyJpegPngWebpMp4Webm: 'Chỉ hỗ trợ JPEG, PNG, WebP, MP4 và WebM.', fileTooLarge: 'Tệp quá lớn.',
    maxAttachments: 'Một bài viết chỉ được có tối đa', attachments: 'tệp đính kèm.', onlyFirstAttachments: 'Chỉ', attachmentsWereAdded: 'tệp đính kèm đầu tiên đã được thêm.',
    unableCreatePost: 'Không thể tạo bài viết.', posts: 'Bài viết', whatsOnMind: 'Bạn đang nghĩ gì', video: 'Video', photoVideo: 'Ảnh/video',
    feelingActivity: 'Cảm xúc/hoạt động', public: 'Công khai', discardPost: 'Bỏ bài viết này?', close: 'Đóng', attachment: 'Tệp đính kèm',
    removeAttachment: 'Xóa tệp đính kèm', posting: 'Đang đăng...', post: 'Đăng',
    unableLoadComments: 'Không thể tải bình luận.', unableUpdateReaction: 'Không thể cập nhật cảm xúc.', unableCreateComment: 'Không thể thêm bình luận.',
    editCommentPrompt: 'Sửa bình luận', unableEditComment: 'Không thể sửa bình luận.', deleteCommentConfirm: 'Xóa bình luận này?',
    unableDeleteComment: 'Không thể xóa bình luận.', editPostPrompt: 'Sửa bài viết', unableEditPost: 'Không thể sửa bài viết.',
    deletePostConfirm: 'Xóa bài viết này?', unableDeletePost: 'Không thể xóa bài viết.', user: 'Người dùng', edit: 'Sửa', delete: 'Xóa',
    browserNoVideo: 'Trình duyệt của bạn không hỗ trợ phát video.', postAttachment: 'Tệp đính kèm bài viết', likes: 'lượt thích', comments: 'bình luận',
    liked: 'Đã thích', like: 'Thích', comment: 'Bình luận', writeComment: 'Viết bình luận', send: 'Gửi', moreOptions: 'Tùy chọn khác',
    shares: 'lượt chia sẻ', shared: 'Đã chia sẻ', share: 'Chia sẻ',
    unableSearchUsers: 'Không thể tìm người dùng.', unableSearchPosts: 'Không thể tìm bài viết.', unableUpdateRelationship: 'Không thể cập nhật mối quan hệ.',
    friends: 'Bạn bè', cancelRequest: 'Hủy lời mời', acceptRequest: 'Chấp nhận', unavailable: 'Không khả dụng', sending: 'Đang gửi...',
    addFriend: 'Thêm bạn', searchPeoplePosts: 'Tìm người và bài viết...', clearSearch: 'Xóa tìm kiếm',
    latestPosts: 'Bài viết mới nhất', searchingPosts: 'Đang tìm bài viết...', noPostsMatching: 'Không tìm thấy bài viết khớp với', noVisiblePostsYet: 'Chưa có bài viết công khai nào.',
    viewAuthor: 'Xem tác giả', reactions: 'cảm xúc', people: 'Mọi người', peopleToDiscover: 'Những người để khám phá', searchingUsers: 'Đang tìm người dùng...',
    noPeopleMatching: 'Không tìm thấy ai khớp với', noUsersDiscover: 'Chưa có người dùng để khám phá.', loadMorePeople: 'Tải thêm người',
    unableLoadConversations: 'Không thể tải cuộc trò chuyện.', unableLoadMessages: 'Không thể tải tin nhắn.', unableCreateConversation: 'Không thể bắt đầu cuộc trò chuyện.',
    unableSendMessage: 'Không thể gửi tin nhắn.', searchMessages: 'Tìm tin nhắn...', findPerson: 'Tìm một người...',
    loadingConversations: 'Đang tải cuộc trò chuyện...', noConversations: 'Chưa có cuộc trò chuyện nào.', unknownUser: 'Người dùng không xác định', startConversation: 'Bắt đầu trò chuyện',
    selectConversation: 'Chọn một cuộc trò chuyện hoặc tạo cuộc trò chuyện mới.', refresh: 'Làm mới', seen: 'Đã xem', isTyping: 'đang nhập',
    noMessagesSayHello: 'Chưa có tin nhắn. Hãy gửi lời chào.', message: 'Nhập tin nhắn...', sendMessage: 'Gửi tin nhắn', now: 'bây giờ',
    quickBreak: 'Nghỉ ngơi một chút', gamesDescription: 'Chơi cờ ca-rô mà không cần rời Fookbase.',
    ticTacToe: 'Cờ ca-rô', youPlayX: 'Bạn chơi X. Máy chơi O.', youWonRound: 'Bạn đã thắng ván này!', computerWonRound: 'Máy đã thắng ván này.',
    drawRound: 'Ván đấu hòa.', yourTurn: 'Lượt của bạn — hãy chọn một ô.', computerThinking: 'Máy đang suy nghĩ…', square: 'Ô',
    newRound: 'Ván mới', resetScore: 'Đặt lại điểm', scoreboard: 'Bảng điểm', you: 'Bạn', draws: 'Hòa', computer: 'Máy',
    howToPlay: 'Cách chơi', gameRuleOne: 'Chọn một ô trống để đặt X.', gameRuleTwo: 'Tạo ba dấu liên tiếp theo hàng, cột hoặc đường chéo.',
    gameRuleThree: 'Bạn có thể bắt đầu ván mới bất cứ lúc nào và giữ nguyên điểm.',
    unableLoadProfile: 'Không thể tải hồ sơ.', accept: 'Chấp nhận', decline: 'Từ chối', unfriend: 'Hủy kết bạn', unblock: 'Bỏ chặn',
    relationshipUnavailable: 'Không thể thao tác với mối quan hệ này', loadingProfile: 'Đang tải hồ sơ...', noCityListed: 'Chưa có thành phố', mutualFriends: 'bạn chung',
    block: 'Chặn', noVisiblePosts: 'Không có bài viết hiển thị.',
    updateProfilePicture: 'Cập nhật ảnh đại diện', uploading: 'Đang tải lên', editCoverPhoto: 'Sửa ảnh bìa', editProfile: 'Chỉnh sửa trang cá nhân',
    accountSecurity: 'Bảo mật tài khoản', security: 'Bảo mật', cancel: 'Hủy', saveProfile: 'Lưu hồ sơ', managePasswordSecurity: 'Quản lý mật khẩu và việc xác minh email của bạn.',
    emailNotVerified: 'Email của bạn chưa được xác minh.', managePosts: 'Quản lý bài viết', loadingPosts: 'Đang tải bài viết...', intro: 'Giới thiệu', noBioYet: 'Chưa có tiểu sử.',
    editBio: 'Sửa tiểu sử', livesIn: 'Sống tại', joined: 'Tham gia', friendsCount: 'bạn bè', editDetails: 'Sửa thông tin', photos: 'Ảnh',
    seeAllPhotos: 'Xem tất cả ảnh', loadingPhotos: 'Đang tải ảnh...', noPhotosPosted: 'Chưa có ảnh nào được đăng.', seeAllFriends: 'Xem tất cả bạn bè',
    noFriendsYet: 'Chưa có bạn bè.', about: 'Giới thiệu', overview: 'Tổng quan', currentCity: 'Thành phố hiện tại', memberSince: 'Thành viên từ', bio: 'Tiểu sử',
    friendRequests: 'Lời mời kết bạn', sentRequests: 'Lời mời đã gửi', blockedUsers: 'Người dùng bị chặn', updating: 'Đang cập nhật...', friendsSince: 'Là bạn từ',
    loadMoreFriends: 'Tải thêm bạn bè', photosFromPosts: 'Ảnh từ bài viết của bạn',
    notSet: 'Chưa thiết lập', displayName: 'Tên hiển thị', currentPassword: 'Mật khẩu hiện tại', newPassword: 'Mật khẩu mới',
    confirmNewPassword: 'Xác nhận mật khẩu mới', saving: 'Đang lưu...', changePassword: 'Đổi mật khẩu', resendVerificationEmail: 'Gửi lại email xác minh',
    passwordChanged: 'Mật khẩu đã được đổi. Các phiên đăng nhập khác đã bị đăng xuất.', verificationResent: 'Email xác minh đã được gửi lại.',
    unableChangePassword: 'Không thể đổi mật khẩu.', unableResendVerification: 'Không thể gửi lại email xác minh.', unableUpdateProfile: 'Không thể cập nhật hồ sơ.',
    unableLoadFriends: 'Không thể tải dữ liệu bạn bè.', unableLoadMoreFriends: 'Không thể tải thêm bạn bè.', unableUpdateProfilePhoto: 'Không thể cập nhật ảnh hồ sơ.',
    unableLoadPosts: 'Không thể tải bài viết.',
    loadMoreComments: 'Tải thêm bình luận',
    loadMoreConversations: 'Tải thêm cuộc trò chuyện', loadMoreMessages: 'Tải thêm tin nhắn',
    invalidProfilePhoto: 'Chỉ hỗ trợ ảnh JPEG, PNG hoặc WebP tối đa 20 MB.',
    retry: 'Thử lại',
    unableSendReport: 'Không thể gửi báo cáo.', reported: 'Đã báo cáo', report: 'Báo cáo', reportUser: 'Báo cáo người dùng', reportPost: 'Báo cáo bài viết',
    reportPrivate: 'Báo cáo của bạn là riêng tư và sẽ được đội ngũ Fookbase xem xét.', closeReportDialog: 'Đóng hộp thoại báo cáo', reason: 'Lý do',
    spam: 'Spam', harassment: 'Quấy rối hoặc bắt nạt', hateSpeech: 'Ngôn từ thù ghét', nudity: 'Nội dung khỏa thân hoặc tình dục', violence: 'Bạo lực hoặc nội dung nguy hiểm',
    scam: 'Lừa đảo hoặc gian lận', other: 'Khác', additionalDetails: 'Thông tin bổ sung', optional: 'không bắt buộc', tellUsWhatHappened: 'Hãy cho chúng tôi biết điều gì đã xảy ra', sendReport: 'Gửi báo cáo',
  },
} as const

interface StoredPreferences {
  language?: AppLanguage
  theme?: AppTheme
}

function getInitialPreferences(): Required<StoredPreferences> {
  try {
    const stored = JSON.parse(localStorage.getItem(preferencesStorageKey) ?? '{}') as StoredPreferences
    const language = stored.language === 'en' || stored.language === 'vi'
      ? stored.language
      : navigator.language.toLowerCase().startsWith('vi') ? 'vi' : 'en'
    const theme = stored.theme === 'light' || stored.theme === 'dark' ? stored.theme : 'dark'
    return { language, theme }
  } catch {
    return { language: navigator.language.toLowerCase().startsWith('vi') ? 'vi' : 'en', theme: 'dark' }
  }
}

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [{ language, theme }, setPreferences] = useState(getInitialPreferences)

  const t = useCallback((key: string) => messages[language][key as keyof typeof messages.en], [language])

  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dataset.theme = theme
    localStorage.setItem(preferencesStorageKey, JSON.stringify({ language, theme }))
  }, [language, theme])

  const value = useMemo<PreferencesContextValue>(() => ({
    language,
    theme,
    setLanguage: (nextLanguage) => setPreferences((current) => ({ ...current, language: nextLanguage })),
    setTheme: (nextTheme) => setPreferences((current) => ({ ...current, theme: nextTheme })),
    t,
  }), [language, theme, t])

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>
}
