// <auto-generated />
using System;
using Fookbase.Api.Modules.Friends.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fookbase.Api.Modules.Friends.Data.Migrations
{
    [DbContext(typeof(FriendsDbContext))]
    [Migration("20260909055039_RemoveFriendsMessaging")]
    partial class RemoveFriendsMessaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fookbase.Api.Modules.Friends.Entities.BlockedUser", b =>
                {
                    b.Property<Guid>("BlockerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BlockerUserId", "BlockedUserId");

                    b.HasIndex("BlockedUserId");

                    b.ToTable("BlockedUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_BlockedUsers_DifferentUsers", "\"BlockerUserId\" <> \"BlockedUserId\"");
                        });
                });

            modelBuilder.Entity("Fookbase.Api.Modules.Friends.Entities.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId1", "UserId2")
                        .IsUnique()
                        .HasDatabaseName("UX_FriendRequests_PendingPair")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("ReceiverUserId", "Status", "CreatedAtUtc");

                    b.HasIndex("SenderUserId", "Status", "CreatedAtUtc");

                    b.ToTable("FriendRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_FriendRequests_CanonicalPair", "\"UserId1\" < \"UserId2\"");

                            t.HasCheckConstraint("CK_FriendRequests_DifferentUsers", "\"SenderUserId\" <> \"ReceiverUserId\"");
                        });
                });

            modelBuilder.Entity("Fookbase.Api.Modules.Friends.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.HasIndex("UserId1", "UserId2")
                        .IsUnique();

                    b.ToTable("Friendships", null, t =>
                        {
                            t.HasCheckConstraint("CK_Friendships_CanonicalPair", "\"UserId1\" < \"UserId2\"");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
